// Self-contained copy for the public marketing landing (pages/index.js).
// This is NOT the app i18n system — it is a deliberate, self-contained marketing
// surface. Each supported language has the SAME set of keys so the UI never goes
// blank when a visitor switches languages.
//
// Inline emphasis is carried as lightweight tokens parsed by the page (no
// dangerouslySetInnerHTML): [b]..[/b] bold, [em]..[/em] italic emphasis,
// [dn]..[/dn] a Devanagari accent span (used only by the code-switched EN hero),
// [br] a line break, and [link]..[/link] the "already live" link.
//
// en is intentionally CODE-SWITCHED (English blended with a few Hindi tokens) and
// reproduces the original page exactly, including the code-switched hero. Every
// other language renders the page FULLY in that language.

export const LANGS = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिन्दी' },
  { code: 'bn', label: 'বাংলা' },
  { code: 'gu', label: 'ગુજરાતી' },
  { code: 'mr', label: 'मराठी' },
  { code: 'ta', label: 'தமிழ்' },
  { code: 'te', label: 'తెలుగు' },
  { code: 'kn', label: 'ಕನ್ನಡ' },
  { code: 'ml', label: 'മലയാളം' },
  { code: 'ur', label: 'اردو' },
];

export const COPY = {
  en: {
    navSignIn: "Sign in",
    navStartFree: "Start free",
    langMenuLabel: "Choose language",
    heroFlag: "Made for Bharat · towns & villages",
    heroH1: "[dn]आपकी दुकान का खाता —[/dn] now on your phone. And it gets you [em]paid.[/em]",
    heroSub: "A digital [b]udhaar[/b] ledger, WhatsApp reminders that collect faster, and a shopfront your customers can order from — in your language, on any phone, free to start.",
    ctaWa: "🟢 WhatsApp पर शुरू करें",
    ctaSignup: "मुफ़्त साइन अप · Sign up free",
    trust2g: "[b]2G[/b] पर चले",
    trustLangs: "[b]10[/b] भाषाएँ",
    trustNoPc: "कंप्यूटर नहीं चाहिए",
    trustFree: "[b]Free[/b] to start",
    phTitle: "आज का हिसाब",
    phName1: "सीता देवी",
    phAmt1: "₹560 बाकी",
    phName2: "रमेश कुमार",
    phAmt2: "₹0 जमा",
    phBubble: "नमस्ते सीता जी 🙏 आपका ₹560 बाकी है। यहाँ से चुकाएँ 👉",
    phSent: "भेजा गया ✓✓",
    probEyebrow: "The problem every dukaandaar knows",
    probH2: "The paper bahi-khata forgets. Customers forget.[br]And that is [em]your[/em] money walking out the door.",
    probLede: "Loose pages, faded pencil, “yaad nahi kitna baaki tha.” Chasing dues is awkward and slow — so a little is lost at every counter, every month. Smart Digital Khata turns that register into a memory that never fades and a reminder that does the asking for you.",
    costEyebrow: "The cost of the paper register",
    costH2: "Small losses, every single day,[br]add up to real money.",
    costLede: "A faded page. A customer who “bhool gaya.” A reminder never sent because it felt awkward. None of it feels big on the day — but count it across a year of counters and it's a serious hole in a hard-earned income.",
    cost1Big: "~₹14,600",
    cost1Cl: "lost in a year if just [b]₹40 of udhaar a day[/b] slips through — forgotten, unread, or never chased.",
    cost2Big: "3–5 hrs",
    cost2Cl: "a week spent adding up the bahi-khata by hand — time that could serve customers or rest.",
    cost3Big: "Awkward",
    cost3Cl: "asking a neighbour for money face-to-face. So many dues are quietly written off.",
    costIllus: "Illustrative — every shop is different. The point isn't the exact number; it's that manual work leaks money and time, quietly, every day. Smart Digital Khata plugs the leak.",
    pillEyebrow: "What you get",
    pillH2: "Three things, one simple app",
    pill1H3: "Digital khata that pays you back",
    pill1P: "Record udhaar in seconds. Automatic WhatsApp & SMS reminders — in the customer's own language — get you paid faster. Cash, UPI or online, all settled in one place.",
    pill1K: "Get paid, not just tracked →",
    pill2H3: "Your shop, discoverable",
    pill2P: "A shopfront customers can browse and order from — you choose pickup, free delivery or a delivery charge. Local commerce for your galli, not a metro q-commerce app.",
    pill2K: "New customers, on your terms →",
    pill3H3: "Truly made for Bharat",
    pill3P: "Ten languages with voice read-aloud, a 1,600-item catalogue in your language, and it works offline on 2G — on the everyday phone already in your pocket. No KYC to begin.",
    pill3K: "Your language, your phone →",
    bandEyebrow: "Where we belong",
    bandH2: "Built for B & C towns and villages —[br]not the metros.",
    bandQ: "Regional-first, lite, and yours. The shopkeeper stays in charge — this is a tool that respects how a kirana already works, and quietly makes it stronger. Not disruption. Digitisation with dignity.",
    bandStat1B: "10",
    bandStat1S: "languages, incl. Hindi, Bengali, Gujarati, Marathi, Tamil, Telugu, Kannada, Malayalam & Urdu",
    bandStat2B: "1,600+",
    bandStat2S: "ready grocery items in your language",
    bandStat3B: "Offline",
    bandStat3S: "works and syncs on flaky 2G",
    bandStat4B: "₹0",
    bandStat4S: "to start — no card, no computer",
    econEyebrow: "The bigger picture",
    econH2: "Digitise one dukaan, and something[br]bigger happens to the whole town.",
    econLede: "A kirana shop isn't just a business — it's the trust, the credit, and the daily lifeline of a mohalla. When it grows stronger, the neighbourhood grows with it.",
    ec1H3: "Money stays in the village",
    ec1P: "Customers buy from the shop down the lane, not a warehouse two cities away. The margin — and the livelihood — stays local instead of leaving town.",
    ec2H3: "Cash flow comes back to life",
    ec2P: "Udhaar collected faster is working capital unstuck. The shopkeeper can restock sooner, extend fair credit, and keep serving neighbours through lean months.",
    ec3H3: "Dignity in your own language",
    ec3P: "A shopkeeper who never touched English software now runs a modern business in Tamil, Telugu, Hindi or Urdu — reading it, hearing it, understood by it. Digital inclusion that actually includes.",
    ec4H3: "The corner shop stays viable",
    ec4P: "Against big chains and metro apps, the trusted local kirana gets the same modern tools — on the phone it already owns. The shop your family knows, future-proofed.",
    econLine: "Every reminder paid, every order fulfilled, every rupee that stays in town — that's a village economy getting a little stronger, one khata at a time.",
    stepsEyebrow: "How it works",
    stepsH2: "Live in five minutes",
    step1H3: "Sign up with your mobile",
    step1P: "Just your phone number and a password or PIN. Change your number later without losing your khata.",
    step2H3: "Add customers & items",
    step2P: "Type them in, or pick from the 1,600-item catalogue shown in your language. Set your own prices.",
    step3H3: "Record, remind, sell",
    step3P: "Note udhaar, let WhatsApp chase the dues, and take orders from your shopfront. See it all on one screen.",
    langEyebrow: "आपकी भाषा में",
    langH2: "The whole app speaks your language",
    langLede: "And when your state's language is ready, we switch it on — carefully reviewed in your language.",
    val1B: "Your data is yours.",
    val1S: "No selling, no spam. Export your khata any time.",
    val2B: "No heavy app.",
    val2S: "Small download, opens fast, kind to your data pack.",
    val3B: "Free to start.",
    val3S: "Upgrade only when it's clearly earning for you.",
    val4B: "You stay in control.",
    val4S: "You decide prices, delivery, reminders — always.",
    nlEyebrow: "Newsletter",
    nlH2: "Tips for dukaandaars — straight to your inbox",
    nlLede: "A short e-mail every few weeks — collecting udhaar, your online shop, and new features in your language. Unsubscribe any time.",
    nlDoneT: "Check your inbox",
    nlDoneS: "We have sent you a link to confirm your subscription.",
    nlPlaceholder: "your@email.com",
    nlAriaEmail: "Email address",
    nlAriaList: "List",
    nlOptCommunity: "Shopkeepers",
    nlOptEcosystem: "Partners / distributors",
    nlSubmit: "Subscribe",
    nlSending: "Sending…",
    nlError: "Something went wrong — please try again.",
    nlNote: "We never sell your e-mail. Double opt-in — confirm before you receive anything.",
    finalEyebrow: "Aaj se shuru karein",
    finalH2: "Give your shop a memory that never forgets.",
    finalLede: "Thousands of counters across Bharat run on udhaar. Make yours run on Smart Digital Khata — free to begin, in your language, today.",
    finalNote: "Already live at [link]khata.dadashaik.com[/link] · works on any Android phone",
    getEyebrow: "Get the app",
    getH2: "Two apps — one for each side of the counter.",
    getLede: "Install free on any Android phone. No computer, no Play Store account needed.",
    getCustT: "For customers",
    getCustP: "See your udhaar at every shop and pay in one tap.",
    getCustBtn: "Get the Customer app",
    getShopT: "For shopkeepers",
    getShopP: "Your khata, collections, and shopfront — in your pocket.",
    getShopBtn: "Get the Shop app",
    getNote: "Android · free · open the link on your phone and tap Install.",
    footTagline: "हर दुकान, अब डिजिटल · Every shop, now digital",
    footBlog: "Blog",
    footCopy: "© Smart Digital Khata",
  },
  hi: {
    navSignIn: "साइन इन",
    navStartFree: "मुफ़्त शुरू करें",
    langMenuLabel: "भाषा चुनें",
    heroFlag: "भारत के लिए बना · कस्बे और गाँव",
    heroH1: "आपकी दुकान का खाता — अब फ़ोन में। और यह आपके पैसे भी [em]दिलाता[/em] है।",
    heroSub: "डिजिटल [b]उधार[/b] खाता, WhatsApp रिमाइंडर जो जल्दी वसूली कराएँ, और एक ऑनलाइन दुकान जहाँ से ग्राहक ऑर्डर करें — आपकी भाषा में, किसी भी फ़ोन पर, शुरू करना मुफ़्त।",
    ctaWa: "🟢 WhatsApp पर शुरू करें",
    ctaSignup: "मुफ़्त साइन अप करें",
    trust2g: "[b]2G[/b] पर चले",
    trustLangs: "[b]10[/b] भाषाएँ",
    trustNoPc: "कंप्यूटर नहीं चाहिए",
    trustFree: "शुरू करना [b]मुफ़्त[/b]",
    phTitle: "आज का हिसाब",
    phName1: "सीता देवी",
    phAmt1: "₹560 बाकी",
    phName2: "रमेश कुमार",
    phAmt2: "₹0 जमा",
    phBubble: "नमस्ते सीता जी 🙏 आपका ₹560 बाकी है। यहाँ से चुकाएँ 👉",
    phSent: "भेजा गया ✓✓",
    probEyebrow: "हर दुकानदार की जानी-पहचानी दिक्कत",
    probH2: "कागज़ का बही-खाता भूल जाता है। ग्राहक भूल जाते हैं।[br]और वह [em]आपका[/em] पैसा है जो दरवाज़े से बाहर चला जाता है।",
    probLede: "ढीले पन्ने, फीकी पेंसिल, “याद नहीं कितना बाकी था।” उधार माँगना अटपटा और धीमा लगता है — तो हर काउंटर पर, हर महीने थोड़ा-थोड़ा खोता रहता है। Smart Digital Khata उस रजिस्टर को ऐसी याद बना देता है जो कभी फीकी नहीं पड़ती, और एक रिमाइंडर जो आपकी ओर से माँग लेता है।",
    costEyebrow: "कागज़ी रजिस्टर की कीमत",
    costH2: "रोज़ का छोटा-छोटा नुकसान[br]मिलकर बड़ी रकम बन जाता है।",
    costLede: "एक फीका पन्ना। एक ग्राहक जो “भूल गया।” एक रिमाइंडर जो अटपटा लगने से कभी भेजा ही नहीं गया। एक दिन में यह बड़ा नहीं लगता — पर साल भर के काउंटरों में जोड़िए तो मेहनत की कमाई में यह बड़ा छेद है।",
    cost1Big: "~₹14,600",
    cost1Cl: "साल भर में गँवाया, अगर रोज़ बस [b]₹40 का उधार[/b] निकल जाए — भूला, बिना पढ़ा, या कभी वसूला ही नहीं।",
    cost2Big: "3–5 घंटे",
    cost2Cl: "हफ़्ते में हाथ से बही-खाता जोड़ने में — वह समय जो ग्राहक की सेवा या आराम में लग सकता था।",
    cost3Big: "अटपटा",
    cost3Cl: "पड़ोसी से आमने-सामने पैसे माँगना। इसी वजह से कितने उधार चुपचाप छोड़ दिए जाते हैं।",
    costIllus: "सिर्फ़ उदाहरण के लिए — हर दुकान अलग है। बात सही आँकड़े की नहीं; बात यह है कि हाथ का काम रोज़ चुपचाप पैसा और समय बहा देता है। Smart Digital Khata उस रिसाव को रोकता है।",
    pillEyebrow: "आपको क्या मिलता है",
    pillH2: "तीन चीज़ें, एक आसान ऐप",
    pill1H3: "डिजिटल खाता जो आपको वापस दिलाता है",
    pill1P: "सेकंडों में उधार लिखें। अपने-आप WhatsApp और SMS रिमाइंडर — ग्राहक की अपनी भाषा में — जल्दी पैसे दिलाते हैं। नकद, UPI या ऑनलाइन, सब एक ही जगह।",
    pill1K: "सिर्फ़ हिसाब नहीं, पैसे भी →",
    pill2H3: "आपकी दुकान, अब सबको दिखे",
    pill2P: "एक ऑनलाइन दुकान जहाँ ग्राहक देखें और ऑर्डर करें — पिकअप, मुफ़्त डिलीवरी या डिलीवरी चार्ज आप तय करें। आपकी गली का लोकल कारोबार, कोई मेट्रो क्विक-कॉमर्स ऐप नहीं।",
    pill2K: "नए ग्राहक, आपकी शर्तों पर →",
    pill3H3: "सच में भारत के लिए बना",
    pill3P: "दस भाषाएँ आवाज़ में पढ़कर सुनाने के साथ, आपकी भाषा में 1,600 सामान की सूची, और 2G पर ऑफ़लाइन भी चले — उसी रोज़मर्रा के फ़ोन पर जो आपकी जेब में है। शुरू करने के लिए कोई KYC नहीं।",
    pill3K: "आपकी भाषा, आपका फ़ोन →",
    bandEyebrow: "हमारी जगह कहाँ है",
    bandH2: "B और C कस्बों और गाँवों के लिए बना —[br]मेट्रो के लिए नहीं।",
    bandQ: "क्षेत्रीय-पहले, हल्का, और आपका अपना। दुकानदार ही मालिक रहता है — यह वह औज़ार है जो किराना के मौजूदा तरीके का सम्मान करता है और उसे चुपचाप मज़बूत बनाता है। तोड़-फोड़ नहीं। इज़्ज़त के साथ डिजिटल होना।",
    bandStat1B: "10",
    bandStat1S: "भाषाएँ, जिनमें हिन्दी, बांग्ला, गुजराती, मराठी, तमिल, तेलुगु, कन्नड़, मलयालम और उर्दू",
    bandStat2B: "1,600+",
    bandStat2S: "आपकी भाषा में तैयार किराना सामान",
    bandStat3B: "ऑफ़लाइन",
    bandStat3S: "कमज़ोर 2G पर भी चले और सिंक हो",
    bandStat4B: "₹0",
    bandStat4S: "शुरू करने के लिए — न कार्ड, न कंप्यूटर",
    econEyebrow: "बड़ी तस्वीर",
    econH2: "एक दुकान को डिजिटल कीजिए, और कुछ[br]बड़ा पूरे कस्बे के साथ होता है।",
    econLede: "किराना दुकान सिर्फ़ धंधा नहीं — वह मोहल्ले का भरोसा, उधार और रोज़ की जीवनरेखा है। जब वह मज़बूत होती है, तो पूरा मोहल्ला उसके साथ बढ़ता है।",
    ec1H3: "पैसा गाँव में ही रहे",
    ec1P: "ग्राहक गली के आख़िर वाली दुकान से खरीदें, दो शहर दूर के गोदाम से नहीं। मुनाफ़ा — और रोज़ी-रोटी — कस्बे से बाहर जाने की बजाय यहीं रहे।",
    ec2H3: "नकदी का बहाव फिर जीवित हो",
    ec2P: "जल्दी वसूला उधार फँसी हुई पूँजी को खोल देता है। दुकानदार जल्दी माल भर सके, सही उधार दे सके, और कम कमाई के महीनों में भी पड़ोसियों की सेवा करता रहे।",
    ec3H3: "अपनी भाषा में इज़्ज़त",
    ec3P: "एक दुकानदार जिसने कभी अंग्रेज़ी सॉफ़्टवेयर छुआ नहीं, अब तमिल, तेलुगु, हिन्दी या उर्दू में आधुनिक कारोबार चलाता है — पढ़ता है, सुनता है, समझा जाता है। ऐसी डिजिटल पहुँच जो सचमुच सबको साथ लेती है।",
    ec4H3: "कोने की दुकान टिकी रहे",
    ec4P: "बड़ी चेन और मेट्रो ऐप के सामने, भरोसेमंद लोकल किराना को वही आधुनिक औज़ार मिलें — उसी फ़ोन पर जो पहले से उसके पास है। आपके परिवार की जानी-पहचानी दुकान, आने वाले कल के लिए तैयार।",
    econLine: "हर वसूला रिमाइंडर, हर पूरा ऑर्डर, हर रुपया जो कस्बे में रहे — यही गाँव की अर्थव्यवस्था को थोड़ा मज़बूत करता है, एक खाता एक बार में।",
    stepsEyebrow: "यह कैसे काम करता है",
    stepsH2: "पाँच मिनट में शुरू",
    step1H3: "अपने मोबाइल से साइन अप करें",
    step1P: "बस आपका फ़ोन नंबर और एक पासवर्ड या PIN। बाद में नंबर बदलें, खाता खोए बिना।",
    step2H3: "ग्राहक और सामान जोड़ें",
    step2P: "टाइप करें, या आपकी भाषा में दिखने वाली 1,600 सामान की सूची से चुनें। अपने दाम खुद तय करें।",
    step3H3: "लिखें, याद दिलाएँ, बेचें",
    step3P: "उधार नोट करें, WhatsApp को वसूली करने दें, और अपनी दुकान से ऑर्डर लें। सब एक ही स्क्रीन पर देखें।",
    langEyebrow: "आपकी भाषा में",
    langH2: "पूरा ऐप आपकी भाषा बोलता है",
    langLede: "और जब आपके राज्य की भाषा तैयार होती है, हम उसे चालू कर देते हैं — आपकी भाषा में ध्यान से जाँच-परख कर।",
    val1B: "आपका डेटा आपका है।",
    val1S: "न बेचना, न स्पैम। अपना खाता कभी भी एक्सपोर्ट करें।",
    val2B: "कोई भारी ऐप नहीं।",
    val2S: "छोटा डाउनलोड, तेज़ खुले, आपके डेटा पैक पर हल्का।",
    val3B: "शुरू करना मुफ़्त।",
    val3S: "अपग्रेड तभी जब यह साफ़ आपके लिए कमाने लगे।",
    val4B: "नियंत्रण आपके हाथ।",
    val4S: "दाम, डिलीवरी, रिमाइंडर — हमेशा आप तय करें।",
    nlEyebrow: "न्यूज़लेटर",
    nlH2: "दुकानदारों के लिए टिप्स — सीधे आपके इनबॉक्स में",
    nlLede: "हर कुछ हफ़्तों में एक छोटा ईमेल — उधार वसूली, ऑनलाइन दुकान और आपकी भाषा में नए फ़ीचर। कभी भी अनसब्सक्राइब करें।",
    nlDoneT: "अपना इनबॉक्स देखें",
    nlDoneS: "पुष्टि के लिए हमने आपको एक लिंक भेजा है।",
    nlPlaceholder: "आपका ईमेल",
    nlAriaEmail: "ईमेल पता",
    nlAriaList: "सूची",
    nlOptCommunity: "दुकानदार",
    nlOptEcosystem: "पार्टनर / वितरक",
    nlSubmit: "सब्सक्राइब करें",
    nlSending: "भेजा जा रहा…",
    nlError: "कुछ गड़बड़ हुई — कृपया फिर कोशिश करें।",
    nlNote: "हम आपका ईमेल कभी नहीं बेचेंगे। डबल ऑप्ट-इन।",
    finalEyebrow: "आज से शुरू करें",
    finalH2: "अपनी दुकान को ऐसी याद दें जो कभी न भूले।",
    finalLede: "भारत भर के हज़ारों काउंटर उधार पर चलते हैं। अपने को Smart Digital Khata पर चलाइए — शुरू करना मुफ़्त, आपकी भाषा में, आज ही।",
    finalNote: "पहले से चालू [link]khata.dadashaik.com[/link] पर · किसी भी Android फ़ोन पर चले",
    getEyebrow: "ऐप पाएँ",
    getH2: "दो ऐप — काउंटर के हर तरफ़ के लिए एक।",
    getLede: "किसी भी Android फ़ोन पर मुफ़्त इंस्टॉल करें। न कंप्यूटर, न Play Store अकाउंट चाहिए।",
    getCustT: "ग्राहकों के लिए",
    getCustP: "हर दुकान का अपना उधार देखें और एक टैप में चुकाएँ।",
    getCustBtn: "ग्राहक ऐप पाएँ",
    getShopT: "दुकानदारों के लिए",
    getShopP: "आपका खाता, वसूली और ऑनलाइन दुकान — आपकी जेब में।",
    getShopBtn: "दुकान ऐप पाएँ",
    getNote: "Android · मुफ़्त · लिंक अपने फ़ोन पर खोलें और Install दबाएँ।",
    footTagline: "हर दुकान, अब डिजिटल · Every shop, now digital",
    footBlog: "ब्लॉग",
    footCopy: "© Smart Digital Khata",
  },
  bn: {
    navSignIn: "সাইন ইন",
    navStartFree: "ফ্রি শুরু করুন",
    langMenuLabel: "ভাষা বেছে নিন",
    heroFlag: "ভারতের জন্য তৈরি · শহরতলি ও গ্রাম",
    heroH1: "আপনার দোকানের খাতা — এবার ফোনেই। আর এটাই আপনাকে টাকা [em]আদায় করে দেয়[/em]।",
    heroSub: "ডিজিটাল [b]ধার[/b] খাতা, WhatsApp রিমাইন্ডার যা দ্রুত টাকা তোলে, আর একটা অনলাইন দোকান যেখান থেকে খদ্দের অর্ডার করবে — আপনার ভাষায়, যে কোনো ফোনে, শুরু করা বিনামূল্যে।",
    ctaWa: "🟢 WhatsApp-এ শুরু করুন",
    ctaSignup: "বিনামূল্যে সাইন আপ করুন",
    trust2g: "[b]2G[/b]-তেও চলে",
    trustLangs: "[b]10[/b]টি ভাষা",
    trustNoPc: "কম্পিউটার লাগে না",
    trustFree: "শুরু করা [b]বিনামূল্যে[/b]",
    phTitle: "আজকের হিসাব",
    phName1: "সীতা দেবী",
    phAmt1: "₹560 বাকি",
    phName2: "রমেশ কুমার",
    phAmt2: "₹0 জমা",
    phBubble: "নমস্কার সীতা দিদি 🙏 আপনার ₹560 বাকি আছে। এখান থেকে মিটিয়ে দিন 👉",
    phSent: "পাঠানো হয়েছে ✓✓",
    probEyebrow: "প্রত্যেক দোকানদারের চেনা সমস্যা",
    probH2: "কাগজের খাতা ভুলে যায়। খদ্দেররাও ভুলে যায়।[br]আর সেটা [em]আপনার[/em] টাকা, দরজা দিয়ে বেরিয়ে যায়।",
    probLede: "আলগা পাতা, ফিকে পেন্সিল, “মনে নেই কত বাকি ছিল।” টাকা চাওয়া অস্বস্তিকর আর ধীর — তাই প্রতি কাউন্টারে, প্রতি মাসে একটু একটু হারিয়ে যায়। Smart Digital Khata সেই খাতাকে এমন স্মৃতি বানায় যা কখনো ফিকে হয় না, আর একটা রিমাইন্ডার যা আপনার হয়ে চেয়ে নেয়।",
    costEyebrow: "কাগজের খাতার দাম",
    costH2: "রোজকার ছোট ছোট ক্ষতি[br]মিলে সত্যিকারের টাকা হয়ে যায়।",
    costLede: "একটা ফিকে পাতা। একজন খদ্দের যে “ভুলে গেছে।” একটা রিমাইন্ডার যা অস্বস্তির জন্য কখনো পাঠানোই হয়নি। একদিনে বড় মনে হয় না — কিন্তু সারা বছরের কাউন্টার জুড়ে যোগ করলে কষ্টের রোজগারে বড় ফুটো।",
    cost1Big: "~₹14,600",
    cost1Cl: "সারা বছরে হারানো, যদি রোজ শুধু [b]₹40 ধার[/b] ফসকে যায় — ভোলা, না-পড়া, বা কখনো আদায় না-করা।",
    cost2Big: "3–5 ঘণ্টা",
    cost2Cl: "সপ্তাহে হাতে খাতা মেলাতে — যে সময় খদ্দেরের সেবা বা বিশ্রামে যেতে পারত।",
    cost3Big: "অস্বস্তি",
    cost3Cl: "প্রতিবেশীর কাছে সামনাসামনি টাকা চাওয়া। এই কারণেই কত ধার চুপচাপ ছেড়ে দেওয়া হয়।",
    costIllus: "শুধু উদাহরণ — প্রতিটি দোকান আলাদা। আসল কথা নিখুঁত সংখ্যা নয়; কথা হলো হাতের কাজ রোজ চুপচাপ টাকা আর সময় বার করে দেয়। Smart Digital Khata সেই ফুটো বন্ধ করে।",
    pillEyebrow: "আপনি কী পাবেন",
    pillH2: "তিনটে জিনিস, একটাই সহজ অ্যাপ",
    pill1H3: "ডিজিটাল খাতা যা আপনাকে ফেরত দেয়",
    pill1P: "সেকেন্ডে ধার লিখুন। নিজে থেকেই WhatsApp আর SMS রিমাইন্ডার — খদ্দেরের নিজের ভাষায় — দ্রুত টাকা এনে দেয়। নগদ, UPI বা অনলাইন, সব এক জায়গায়।",
    pill1K: "শুধু হিসাব নয়, টাকাও →",
    pill2H3: "আপনার দোকান, এবার সবার চোখে",
    pill2P: "একটা অনলাইন দোকান যেখানে খদ্দের দেখে অর্ডার করবে — পিকআপ, ফ্রি ডেলিভারি বা ডেলিভারি চার্জ আপনি ঠিক করবেন। আপনার গলির স্থানীয় ব্যবসা, কোনো মেট্রো কুইক-কমার্স অ্যাপ নয়।",
    pill2K: "নতুন খদ্দের, আপনার শর্তে →",
    pill3H3: "সত্যিই ভারতের জন্য তৈরি",
    pill3P: "দশটি ভাষা কণ্ঠে পড়ে শোনানোর সঙ্গে, আপনার ভাষায় 1,600 জিনিসের তালিকা, আর 2G-তে অফলাইনেও চলে — আপনার পকেটের রোজকার ফোনেই। শুরু করতে কোনো KYC নয়।",
    pill3K: "আপনার ভাষা, আপনার ফোন →",
    bandEyebrow: "আমাদের জায়গা কোথায়",
    bandH2: "B ও C শহরতলি আর গ্রামের জন্য —[br]মেট্রোর জন্য নয়।",
    bandQ: "আঞ্চলিক-আগে, হালকা, আর আপনার নিজের। দোকানদারই মালিক থাকে — এটা এমন একটা যন্ত্র যা কিরানার চেনা ধরনকে সম্মান করে আর চুপচাপ তাকে শক্ত করে। ভাঙচুর নয়। সম্মানের সঙ্গে ডিজিটাল হওয়া।",
    bandStat1B: "10",
    bandStat1S: "ভাষা, যার মধ্যে হিন্দি, বাংলা, গুজরাটি, মারাঠি, তামিল, তেলুগু, কন্নড়, মালয়ালম ও উর্দু",
    bandStat2B: "1,600+",
    bandStat2S: "আপনার ভাষায় তৈরি মুদির জিনিস",
    bandStat3B: "অফলাইন",
    bandStat3S: "দুর্বল 2G-তেও চলে ও সিঙ্ক হয়",
    bandStat4B: "₹0",
    bandStat4S: "শুরু করতে — কার্ড নয়, কম্পিউটার নয়",
    econEyebrow: "বড় ছবিটা",
    econH2: "একটা দোকান ডিজিটাল করুন, আর কিছু[br]বড় গোটা শহরের সঙ্গে ঘটে।",
    econLede: "কিরানা দোকান শুধু ব্যবসা নয় — এটা পাড়ার বিশ্বাস, ধার, আর রোজকার প্রাণভোমরা। এটা শক্ত হলে, গোটা পাড়া তার সঙ্গে বাড়ে।",
    ec1H3: "টাকা গ্রামেই থাকে",
    ec1P: "খদ্দের গলির শেষের দোকান থেকে কেনে, দু-শহর দূরের গুদাম থেকে নয়। মুনাফা — আর রুজি — শহর ছেড়ে না গিয়ে এখানেই থাকে।",
    ec2H3: "নগদের চলা ফিরে আসে",
    ec2P: "দ্রুত আদায় করা ধার আটকে থাকা মূলধন খুলে দেয়। দোকানদার তাড়াতাড়ি মাল ভরতে পারে, ন্যায্য ধার দিতে পারে, আর কম রোজগারের মাসেও প্রতিবেশীর সেবা করতে পারে।",
    ec3H3: "নিজের ভাষায় সম্মান",
    ec3P: "যে দোকানদার কখনো ইংরেজি সফটওয়্যার ছোঁননি, তিনি এখন তামিল, তেলুগু, হিন্দি বা উর্দুতে আধুনিক ব্যবসা চালান — পড়েন, শোনেন, বোঝা যায়। এমন ডিজিটাল অন্তর্ভুক্তি যা সত্যিই সবাইকে নেয়।",
    ec4H3: "কোণের দোকান টিকে থাকে",
    ec4P: "বড় চেন আর মেট্রো অ্যাপের সামনে, বিশ্বাসী স্থানীয় কিরানা সেই একই আধুনিক যন্ত্র পায় — নিজের ফোনেই। আপনার পরিবারের চেনা দোকান, আগামীর জন্য তৈরি।",
    econLine: "প্রতিটি আদায় হওয়া রিমাইন্ডার, প্রতিটি পূরণ হওয়া অর্ডার, প্রতিটি টাকা যা শহরে থাকে — এটাই গ্রামের অর্থনীতিকে একটু শক্ত করে, একটা খাতা এক-এক করে।",
    stepsEyebrow: "এটা কীভাবে কাজ করে",
    stepsH2: "পাঁচ মিনিটে চালু",
    step1H3: "আপনার মোবাইল দিয়ে সাইন আপ করুন",
    step1P: "শুধু আপনার ফোন নম্বর আর একটা পাসওয়ার্ড বা PIN। পরে নম্বর বদলান, খাতা না হারিয়ে।",
    step2H3: "খদ্দের ও জিনিস যোগ করুন",
    step2P: "টাইপ করুন, বা আপনার ভাষায় দেখানো 1,600 জিনিসের তালিকা থেকে বেছে নিন। নিজের দাম নিজে ঠিক করুন।",
    step3H3: "লিখুন, মনে করান, বিক্রি করুন",
    step3P: "ধার নোট করুন, WhatsApp-কে টাকা তুলতে দিন, আর দোকান থেকে অর্ডার নিন। সব এক স্ক্রিনে দেখুন।",
    langEyebrow: "আপনার ভাষায়",
    langH2: "গোটা অ্যাপ আপনার ভাষায় কথা বলে",
    langLede: "আর যখন আপনার রাজ্যের ভাষা তৈরি হয়, আমরা সেটা চালু করি — আপনার ভাষায় যত্ন করে যাচাই করে।",
    val1B: "আপনার তথ্য আপনার।",
    val1S: "বিক্রি নয়, স্প্যাম নয়। খাতা যখন খুশি এক্সপোর্ট করুন।",
    val2B: "ভারী অ্যাপ নয়।",
    val2S: "ছোট ডাউনলোড, দ্রুত খোলে, আপনার ডেটা প্যাকে হালকা।",
    val3B: "শুরু করা বিনামূল্যে।",
    val3S: "আপগ্রেড তখনই যখন এটা স্পষ্ট আপনার জন্য রোজগার করে।",
    val4B: "নিয়ন্ত্রণ আপনার হাতে।",
    val4S: "দাম, ডেলিভারি, রিমাইন্ডার — সবসময় আপনি ঠিক করেন।",
    nlEyebrow: "নিউজলেটার",
    nlH2: "দোকানদারদের জন্য টিপস — সরাসরি আপনার ইনবক্সে",
    nlLede: "কয়েক সপ্তাহে একটা ছোট ইমেল — ধার আদায়, অনলাইন দোকান আর আপনার ভাষায় নতুন ফিচার। যখন খুশি আনসাবস্ক্রাইব করুন।",
    nlDoneT: "আপনার ইনবক্স দেখুন",
    nlDoneS: "নিশ্চিত করতে আমরা আপনাকে একটা লিঙ্ক পাঠিয়েছি।",
    nlPlaceholder: "আপনার ইমেল",
    nlAriaEmail: "ইমেল ঠিকানা",
    nlAriaList: "তালিকা",
    nlOptCommunity: "দোকানদার",
    nlOptEcosystem: "পার্টনার / পরিবেশক",
    nlSubmit: "সাবস্ক্রাইব করুন",
    nlSending: "পাঠানো হচ্ছে…",
    nlError: "কিছু ভুল হলো — অনুগ্রহ করে আবার চেষ্টা করুন।",
    nlNote: "আমরা আপনার ইমেল কখনো বিক্রি করি না। ডাবল অপ্ট-ইন।",
    finalEyebrow: "আজ থেকে শুরু করুন",
    finalH2: "আপনার দোকানকে এমন স্মৃতি দিন যা কখনো ভোলে না।",
    finalLede: "ভারত জুড়ে হাজারো কাউন্টার ধারে চলে। আপনারটা Smart Digital Khata-য় চালান — শুরু বিনামূল্যে, আপনার ভাষায়, আজই।",
    finalNote: "আগে থেকেই চালু [link]khata.dadashaik.com[/link]-এ · যে কোনো Android ফোনে চলে",
    getEyebrow: "অ্যাপ নিন",
    getH2: "দুটো অ্যাপ — কাউন্টারের দুই দিকের জন্য একটা করে।",
    getLede: "যে কোনো Android ফোনে বিনামূল্যে ইনস্টল করুন। কম্পিউটার নয়, Play Store অ্যাকাউন্টও লাগে না।",
    getCustT: "খদ্দেরদের জন্য",
    getCustP: "প্রতিটি দোকানে আপনার ধার দেখুন আর এক ট্যাপে মিটিয়ে দিন।",
    getCustBtn: "খদ্দের অ্যাপ নিন",
    getShopT: "দোকানদারদের জন্য",
    getShopP: "আপনার খাতা, আদায় আর অনলাইন দোকান — আপনার পকেটে।",
    getShopBtn: "দোকান অ্যাপ নিন",
    getNote: "Android · বিনামূল্যে · লিঙ্কটা আপনার ফোনে খুলে Install-এ চাপ দিন।",
    footTagline: "প্রতিটি দোকান, এবার ডিজিটাল · Every shop, now digital",
    footBlog: "ব্লগ",
    footCopy: "© Smart Digital Khata",
  },
  gu: {
    navSignIn: "સાઇન ઇન",
    navStartFree: "મફત શરૂ કરો",
    langMenuLabel: "ભાષા પસંદ કરો",
    heroFlag: "ભારત માટે બનેલું · નગરો અને ગામડાં",
    heroH1: "તમારી દુકાનનું ખાતું — હવે ફોનમાં. અને એ જ તમને પૈસા [em]અપાવે[/em] છે.",
    heroSub: "ડિજિટલ [b]ઉધાર[/b] ખાતું, WhatsApp રિમાઇન્ડર જે ઝડપથી વસૂલી કરાવે, અને એક ઓનલાઇન દુકાન જ્યાંથી ગ્રાહક ઓર્ડર કરે — તમારી ભાષામાં, કોઈ પણ ફોન પર, શરૂ કરવું મફત.",
    ctaWa: "🟢 WhatsApp પર શરૂ કરો",
    ctaSignup: "મફત સાઇન અપ કરો",
    trust2g: "[b]2G[/b] પર ચાલે",
    trustLangs: "[b]10[/b] ભાષાઓ",
    trustNoPc: "કમ્પ્યુટર જોઈએ નહીં",
    trustFree: "શરૂ કરવું [b]મફત[/b]",
    phTitle: "આજનો હિસાબ",
    phName1: "સીતા દેવી",
    phAmt1: "₹560 બાકી",
    phName2: "રમેશ કુમાર",
    phAmt2: "₹0 જમા",
    phBubble: "નમસ્તે સીતાબેન 🙏 તમારા ₹560 બાકી છે. અહીંથી ચૂકવો 👉",
    phSent: "મોકલ્યું ✓✓",
    probEyebrow: "દરેક દુકાનદારની જાણીતી તકલીફ",
    probH2: "કાગળનું ચોપડું ભૂલી જાય છે. ગ્રાહકો ભૂલી જાય છે.[br]અને એ [em]તમારા[/em] પૈસા છે જે દરવાજેથી બહાર જાય છે.",
    probLede: "છૂટા પાનાં, ઝાંખી પેન્સિલ, “યાદ નથી કેટલા બાકી હતા.” ઉધાર માગવું અઘરું અને ધીમું લાગે — તો દરેક કાઉન્ટર પર, દર મહિને થોડું થોડું ખોવાય. Smart Digital Khata એ ચોપડાને એવી યાદ બનાવે જે કદી ઝાંખી ના પડે, અને એક રિમાઇન્ડર જે તમારા વતી માગી લે.",
    costEyebrow: "કાગળના ચોપડાની કિંમત",
    costH2: "રોજનું નાનું નાનું નુકસાન[br]ભેગું થઈ સાચા પૈસા બની જાય.",
    costLede: "એક ઝાંખું પાનું. એક ગ્રાહક જે “ભૂલી ગયો.” એક રિમાઇન્ડર જે અઘરું લાગવાથી કદી મોકલાયું જ નહીં. એક દિવસમાં મોટું ના લાગે — પણ આખા વર્ષના કાઉન્ટરમાં ગણો તો મહેનતની કમાણીમાં મોટું છિદ્ર.",
    cost1Big: "~₹14,600",
    cost1Cl: "વર્ષમાં ગુમાવ્યા, જો રોજ ફક્ત [b]₹40 ઉધાર[/b] સરકી જાય — ભૂલાયું, ના વંચાયું, કે કદી વસૂલ્યું જ નહીં.",
    cost2Big: "3–5 કલાક",
    cost2Cl: "અઠવાડિયે હાથે ચોપડું સરવાળવામાં — એ સમય જે ગ્રાહકની સેવા કે આરામમાં જઈ શકે.",
    cost3Big: "અઘરું",
    cost3Cl: "પડોશી પાસે સામસામે પૈસા માગવા. એ જ કારણે કેટલાય ઉધાર ચૂપચાપ છોડી દેવાય.",
    costIllus: "ફક્ત ઉદાહરણ — દરેક દુકાન અલગ. વાત સાચા આંકડાની નથી; વાત એ છે કે હાથનું કામ રોજ ચૂપચાપ પૈસા ને સમય વહાવે. Smart Digital Khata એ ગળતર બંધ કરે.",
    pillEyebrow: "તમને શું મળે",
    pillH2: "ત્રણ વસ્તુ, એક સહેલી એપ",
    pill1H3: "ડિજિટલ ખાતું જે તમને પાછું આપે",
    pill1P: "સેકન્ડમાં ઉધાર લખો. આપોઆપ WhatsApp અને SMS રિમાઇન્ડર — ગ્રાહકની પોતાની ભાષામાં — ઝડપથી પૈસા અપાવે. રોકડ, UPI કે ઓનલાઇન, બધું એક જ જગ્યાએ.",
    pill1K: "ફક્ત હિસાબ નહીં, પૈસા પણ →",
    pill2H3: "તમારી દુકાન, હવે સૌને દેખાય",
    pill2P: "એક ઓનલાઇન દુકાન જ્યાં ગ્રાહક જુએ ને ઓર્ડર કરે — પિકઅપ, મફત ડિલિવરી કે ડિલિવરી ચાર્જ તમે નક્કી કરો. તમારી ગલીનો સ્થાનિક ધંધો, કોઈ મેટ્રો ક્વિક-કોમર્સ એપ નહીં.",
    pill2K: "નવા ગ્રાહક, તમારી શરતે →",
    pill3H3: "ખરેખર ભારત માટે બનેલું",
    pill3P: "દસ ભાષાઓ અવાજમાં વાંચી સંભળાવવા સાથે, તમારી ભાષામાં 1,600 વસ્તુની યાદી, અને 2G પર ઓફલાઇન પણ ચાલે — તમારા ખિસ્સાના રોજિંદા ફોન પર જ. શરૂ કરવા કોઈ KYC નહીં.",
    pill3K: "તમારી ભાષા, તમારો ફોન →",
    bandEyebrow: "અમારી જગ્યા ક્યાં",
    bandH2: "B અને C નગરો ને ગામડાં માટે —[br]મેટ્રો માટે નહીં.",
    bandQ: "પ્રાદેશિક-પહેલા, હળવું, ને તમારું પોતાનું. દુકાનદાર જ માલિક રહે — આ એવું સાધન છે જે કિરાણાની હાલની રીતને માન આપે ને ચૂપચાપ મજબૂત કરે. તોડફોડ નહીં. માન સાથે ડિજિટલ થવું.",
    bandStat1B: "10",
    bandStat1S: "ભાષાઓ, જેમાં હિન્દી, બંગાળી, ગુજરાતી, મરાઠી, તમિળ, તેલુગુ, કન્નડ, મલયાલમ ને ઉર્દૂ",
    bandStat2B: "1,600+",
    bandStat2S: "તમારી ભાષામાં તૈયાર કરિયાણાની વસ્તુઓ",
    bandStat3B: "ઓફલાઇન",
    bandStat3S: "નબળા 2G પર પણ ચાલે ને સિંક થાય",
    bandStat4B: "₹0",
    bandStat4S: "શરૂ કરવા — કાર્ડ નહીં, કમ્પ્યુટર નહીં",
    econEyebrow: "મોટું ચિત્ર",
    econH2: "એક દુકાનને ડિજિટલ કરો, અને કંઈક[br]મોટું આખા નગર સાથે થાય.",
    econLede: "કિરાણાની દુકાન ફક્ત ધંધો નથી — એ મહોલ્લાનો ભરોસો, ઉધાર ને રોજની જીવાદોરી છે. એ મજબૂત થાય, ત્યારે આખો મહોલ્લો એની સાથે વધે.",
    ec1H3: "પૈસા ગામમાં જ રહે",
    ec1P: "ગ્રાહક ગલીના છેડાની દુકાનેથી ખરીદે, બે શહેર દૂરના ગોડાઉનેથી નહીં. નફો — ને રોજી — શહેર છોડ્યા વગર અહીં જ રહે.",
    ec2H3: "રોકડનો પ્રવાહ ફરી જીવે",
    ec2P: "ઝડપથી વસૂલ ઉધાર ફસાયેલી મૂડી છોડાવે. દુકાનદાર વહેલો માલ ભરે, વાજબી ઉધાર આપે, ને ઓછી કમાણીના મહિનામાં પણ પડોશીની સેવા કરે.",
    ec3H3: "પોતાની ભાષામાં માન",
    ec3P: "જે દુકાનદારે કદી અંગ્રેજી સોફ્ટવેર અડ્યું નહોતું, એ હવે તમિળ, તેલુગુ, હિન્દી કે ઉર્દૂમાં આધુનિક ધંધો ચલાવે — વાંચે, સાંભળે, સમજાય. એવો ડિજિટલ સમાવેશ જે ખરેખર સૌને લે.",
    ec4H3: "ખૂણાની દુકાન ટકી રહે",
    ec4P: "મોટી ચેન ને મેટ્રો એપ સામે, ભરોસાપાત્ર સ્થાનિક કિરાણાને એ જ આધુનિક સાધન મળે — પોતાના ફોન પર જ. તમારા પરિવારની જાણીતી દુકાન, આવતી કાલ માટે તૈયાર.",
    econLine: "દરેક વસૂલ થયેલ રિમાઇન્ડર, દરેક પૂરો થયેલ ઓર્ડર, દરેક રૂપિયો જે નગરમાં રહે — એ જ ગામની અર્થવ્યવસ્થાને થોડી મજબૂત કરે, એક ખાતું એક વખતે.",
    stepsEyebrow: "એ કેવી રીતે કામ કરે",
    stepsH2: "પાંચ મિનિટમાં ચાલુ",
    step1H3: "તમારા મોબાઇલથી સાઇન અપ કરો",
    step1P: "ફક્ત તમારો ફોન નંબર ને એક પાસવર્ડ કે PIN. પછી નંબર બદલો, ખાતું ગુમાવ્યા વગર.",
    step2H3: "ગ્રાહક ને વસ્તુ ઉમેરો",
    step2P: "ટાઇપ કરો, કે તમારી ભાષામાં દેખાતી 1,600 વસ્તુની યાદીમાંથી પસંદ કરો. તમારા ભાવ જાતે નક્કી કરો.",
    step3H3: "લખો, યાદ કરાવો, વેચો",
    step3P: "ઉધાર નોંધો, WhatsApp ને વસૂલી કરવા દો, ને તમારી દુકાનેથી ઓર્ડર લો. બધું એક જ સ્ક્રીન પર જુઓ.",
    langEyebrow: "તમારી ભાષામાં",
    langH2: "આખી એપ તમારી ભાષા બોલે",
    langLede: "અને જ્યારે તમારા રાજ્યની ભાષા તૈયાર થાય, અમે એ ચાલુ કરીએ — તમારી ભાષામાં ધ્યાનથી ચકાસીને.",
    val1B: "તમારો ડેટા તમારો.",
    val1S: "ના વેચાણ, ના સ્પામ. ખાતું ગમે ત્યારે એક્સપોર્ટ કરો.",
    val2B: "ભારે એપ નહીં.",
    val2S: "નાનું ડાઉનલોડ, ઝડપથી ખૂલે, તમારા ડેટા પેક પર હળવું.",
    val3B: "શરૂ કરવું મફત.",
    val3S: "અપગ્રેડ ત્યારે જ જ્યારે એ સ્પષ્ટ તમારા માટે કમાય.",
    val4B: "કાબૂ તમારા હાથમાં.",
    val4S: "ભાવ, ડિલિવરી, રિમાઇન્ડર — હંમેશા તમે નક્કી કરો.",
    nlEyebrow: "ન્યૂઝલેટર",
    nlH2: "દુકાનદારો માટે ટિપ્સ — સીધું તમારા ઇનબોક્સમાં",
    nlLede: "થોડા અઠવાડિયે એક નાનું ઇમેલ — ઉધાર વસૂલી, ઓનલાઇન દુકાન ને તમારી ભાષામાં નવા ફીચર. ગમે ત્યારે અનસબ્સ્ક્રાઇબ કરો.",
    nlDoneT: "તમારું ઇનબોક્સ જુઓ",
    nlDoneS: "ખાતરી માટે અમે તમને એક લિંક મોકલી છે.",
    nlPlaceholder: "તમારું ઇમેલ",
    nlAriaEmail: "ઇમેલ સરનામું",
    nlAriaList: "યાદી",
    nlOptCommunity: "દુકાનદારો",
    nlOptEcosystem: "પાર્ટનર / વિતરક",
    nlSubmit: "સબ્સ્ક્રાઇબ કરો",
    nlSending: "મોકલાઈ રહ્યું…",
    nlError: "કંઈક ખોટું થયું — કૃપા કરી ફરી પ્રયાસ કરો.",
    nlNote: "અમે તમારું ઇમેલ કદી વેચીશું નહીં. ડબલ ઓપ્ટ-ઇન.",
    finalEyebrow: "આજથી શરૂ કરો",
    finalH2: "તમારી દુકાનને એવી યાદ આપો જે કદી ના ભૂલે.",
    finalLede: "ભારતભરના હજારો કાઉન્ટર ઉધાર પર ચાલે. તમારું Smart Digital Khata પર ચલાવો — શરૂ મફત, તમારી ભાષામાં, આજે જ.",
    finalNote: "પહેલેથી ચાલુ [link]khata.dadashaik.com[/link] પર · કોઈ પણ Android ફોન પર ચાલે",
    getEyebrow: "એપ મેળવો",
    getH2: "બે એપ — કાઉન્ટરની બંને બાજુ માટે એક એક.",
    getLede: "કોઈ પણ Android ફોન પર મફત ઇન્સ્ટોલ કરો. કમ્પ્યુટર નહીં, Play Store એકાઉન્ટ પણ જોઈએ નહીં.",
    getCustT: "ગ્રાહકો માટે",
    getCustP: "દરેક દુકાનનું તમારું ઉધાર જુઓ અને એક ટૅપમાં ચૂકવો.",
    getCustBtn: "ગ્રાહક એપ મેળવો",
    getShopT: "દુકાનદારો માટે",
    getShopP: "તમારું ખાતું, વસૂલી અને ઓનલાઇન દુકાન — તમારા ખિસ્સામાં.",
    getShopBtn: "દુકાન એપ મેળવો",
    getNote: "Android · મફત · લિંક તમારા ફોન પર ખોલો અને Install દબાવો.",
    footTagline: "દરેક દુકાન, હવે ડિજિટલ · Every shop, now digital",
    footBlog: "બ્લોગ",
    footCopy: "© Smart Digital Khata",
  },
  mr: {
    navSignIn: "साइन इन",
    navStartFree: "मोफत सुरू करा",
    langMenuLabel: "भाषा निवडा",
    heroFlag: "भारतासाठी बनवलेले · गावे आणि छोटी शहरे",
    heroH1: "तुमच्या दुकानाचं खातं — आता फोनमध्ये. आणि तेच तुम्हाला पैसे [em]मिळवून देतं[/em].",
    heroSub: "डिजिटल [b]उधारी[/b] खातं, WhatsApp स्मरणपत्रं जी लवकर वसुली करतात, आणि एक ऑनलाइन दुकान जिथून ग्राहक ऑर्डर करतात — तुमच्या भाषेत, कोणत्याही फोनवर, सुरू करणं मोफत.",
    ctaWa: "🟢 WhatsApp वर सुरू करा",
    ctaSignup: "मोफत साइन अप करा",
    trust2g: "[b]2G[/b] वर चालतं",
    trustLangs: "[b]10[/b] भाषा",
    trustNoPc: "संगणक लागत नाही",
    trustFree: "सुरू करणं [b]मोफत[/b]",
    phTitle: "आजचा हिशोब",
    phName1: "सीता देवी",
    phAmt1: "₹560 बाकी",
    phName2: "रमेश कुमार",
    phAmt2: "₹0 जमा",
    phBubble: "नमस्कार सीताताई 🙏 तुमचे ₹560 बाकी आहेत. इथून भरा 👉",
    phSent: "पाठवले ✓✓",
    probEyebrow: "प्रत्येक दुकानदाराला माहीत असलेली अडचण",
    probH2: "कागदी वहीखातं विसरतं. ग्राहकही विसरतात.[br]आणि ते [em]तुमचे[/em] पैसे दारातून बाहेर जातात.",
    probLede: "सुटी पानं, फिकट पेन्सिल, “किती बाकी होतं आठवत नाही.” उधारी मागणं अवघड आणि सावकाश वाटतं — म्हणून प्रत्येक काउंटरवर, दर महिन्याला थोडं थोडं हरवतं. Smart Digital Khata त्या वहीला अशी आठवण बनवतं जी कधी फिकट होत नाही, आणि एक स्मरणपत्र जे तुमच्या वतीने मागतं.",
    costEyebrow: "कागदी वहीची किंमत",
    costH2: "रोजचं छोटं छोटं नुकसान[br]मिळून खरे पैसे होतात.",
    costLede: "एक फिकट पान. एक ग्राहक जो “विसरला.” एक स्मरणपत्र जे अवघड वाटल्याने कधी पाठवलंच नाही. एका दिवसात मोठं वाटत नाही — पण वर्षभराच्या काउंटरात मोजा तर मेहनतीच्या कमाईत मोठं भोक.",
    cost1Big: "~₹14,600",
    cost1Cl: "वर्षात गमावले, जर रोज फक्त [b]₹40 उधारी[/b] सटकली तर — विसरलेली, न वाचलेली, किंवा कधी न वसूल केलेली.",
    cost2Big: "3–5 तास",
    cost2Cl: "आठवड्याला हाताने वही जुळवण्यात — तो वेळ जो ग्राहकसेवेत किंवा विश्रांतीत जाऊ शकतो.",
    cost3Big: "अवघड",
    cost3Cl: "शेजाऱ्याकडे समोरासमोर पैसे मागणं. याच कारणाने किती उधारी गपचूप सोडून दिली जाते.",
    costIllus: "फक्त उदाहरण — प्रत्येक दुकान वेगळं. मुद्दा नेमक्या आकड्याचा नाही; मुद्दा हा की हाताचं काम रोज गपचूप पैसे आणि वेळ गाळतं. Smart Digital Khata ती गळती थांबवतं.",
    pillEyebrow: "तुम्हाला काय मिळतं",
    pillH2: "तीन गोष्टी, एकच सोपं अ‍ॅप",
    pill1H3: "डिजिटल खातं जे तुम्हाला परत देतं",
    pill1P: "सेकंदात उधारी लिहा. आपोआप WhatsApp आणि SMS स्मरणपत्रं — ग्राहकाच्या स्वतःच्या भाषेत — लवकर पैसे मिळवून देतात. रोख, UPI किंवा ऑनलाइन, सगळं एकाच ठिकाणी.",
    pill1K: "फक्त हिशोब नाही, पैसेही →",
    pill2H3: "तुमचं दुकान, आता सर्वांना दिसतं",
    pill2P: "एक ऑनलाइन दुकान जिथे ग्राहक बघतात आणि ऑर्डर करतात — पिकअप, मोफत डिलिव्हरी किंवा डिलिव्हरी चार्ज तुम्ही ठरवा. तुमच्या गल्लीचा स्थानिक व्यवसाय, कोणतंही मेट्रो क्विक-कॉमर्स अ‍ॅप नाही.",
    pill2K: "नवे ग्राहक, तुमच्या अटींवर →",
    pill3H3: "खरोखर भारतासाठी बनवलेलं",
    pill3P: "दहा भाषा आवाजात वाचून दाखवण्यासह, तुमच्या भाषेत 1,600 वस्तूंची यादी, आणि 2G वर ऑफलाइनही चालतं — तुमच्या खिशातल्या रोजच्या फोनवरच. सुरू करायला KYC नाही.",
    pill3K: "तुमची भाषा, तुमचा फोन →",
    bandEyebrow: "आमची जागा कुठे",
    bandH2: "B आणि C शहरं आणि गावांसाठी —[br]मेट्रोसाठी नाही.",
    bandQ: "प्रादेशिक-आधी, हलकं, आणि तुमचं स्वतःचं. दुकानदारच मालक राहतो — हे असं साधन आहे जे किराणाच्या सध्याच्या पद्धतीचा मान राखतं आणि गपचूप बळकट करतं. मोडतोड नाही. सन्मानाने डिजिटल होणं.",
    bandStat1B: "10",
    bandStat1S: "भाषा, ज्यात हिंदी, बंगाली, गुजराती, मराठी, तमिळ, तेलुगू, कन्नड, मल्याळम आणि उर्दू",
    bandStat2B: "1,600+",
    bandStat2S: "तुमच्या भाषेत तयार किराणा वस्तू",
    bandStat3B: "ऑफलाइन",
    bandStat3S: "कमकुवत 2G वरही चालतं आणि सिंक होतं",
    bandStat4B: "₹0",
    bandStat4S: "सुरू करायला — कार्ड नाही, संगणक नाही",
    econEyebrow: "मोठं चित्र",
    econH2: "एक दुकान डिजिटल करा, आणि काहीतरी[br]मोठं संपूर्ण गावासोबत घडतं.",
    econLede: "किराणा दुकान म्हणजे फक्त व्यवसाय नाही — तो मोहल्ल्याचा विश्वास, उधारी आणि रोजची जीवनरेखा आहे. ते बळकट होतं, तेव्हा संपूर्ण शेजार त्यासोबत वाढतो.",
    ec1H3: "पैसा गावातच राहतो",
    ec1P: "ग्राहक गल्लीच्या टोकाच्या दुकानातून घेतो, दोन शहरं दूरच्या गोदामातून नाही. नफा — आणि उपजीविका — गाव सोडून न जाता इथेच राहते.",
    ec2H3: "रोख रकमेचा प्रवाह पुन्हा जिवंत होतो",
    ec2P: "लवकर वसूल केलेली उधारी अडकलेलं भांडवल मोकळं करते. दुकानदार लवकर माल भरतो, योग्य उधार देतो, आणि कमी कमाईच्या महिन्यांतही शेजाऱ्यांची सेवा करतो.",
    ec3H3: "स्वतःच्या भाषेत सन्मान",
    ec3P: "ज्या दुकानदाराने कधी इंग्रजी सॉफ्टवेअरला हात लावला नाही, तो आता तमिळ, तेलुगू, हिंदी किंवा उर्दूमध्ये आधुनिक व्यवसाय चालवतो — वाचतो, ऐकतो, समजून घेतला जातो. असा डिजिटल समावेश जो खरोखर सर्वांना घेतो.",
    ec4H3: "कोपऱ्यावरचं दुकान टिकून राहतं",
    ec4P: "मोठ्या साखळ्या आणि मेट्रो अ‍ॅपसमोर, विश्वासू स्थानिक किराणाला तीच आधुनिक साधनं मिळतात — स्वतःच्या फोनवरच. तुमच्या कुटुंबाला माहीत असलेलं दुकान, उद्यासाठी तयार.",
    econLine: "प्रत्येक वसूल झालेलं स्मरणपत्र, प्रत्येक पूर्ण झालेली ऑर्डर, प्रत्येक रुपया जो गावात राहतो — तोच गावाची अर्थव्यवस्था थोडी बळकट करतो, एक खातं एका वेळी.",
    stepsEyebrow: "हे कसं काम करतं",
    stepsH2: "पाच मिनिटांत सुरू",
    step1H3: "तुमच्या मोबाइलने साइन अप करा",
    step1P: "फक्त तुमचा फोन नंबर आणि एक पासवर्ड किंवा PIN. नंतर नंबर बदला, खातं न गमावता.",
    step2H3: "ग्राहक आणि वस्तू जोडा",
    step2P: "टाइप करा, किंवा तुमच्या भाषेत दिसणाऱ्या 1,600 वस्तूंच्या यादीतून निवडा. तुमचे भाव स्वतः ठरवा.",
    step3H3: "लिहा, आठवण करा, विका",
    step3P: "उधारी नोंदवा, WhatsApp ला वसुली करू द्या, आणि तुमच्या दुकानातून ऑर्डर घ्या. सगळं एकाच स्क्रीनवर बघा.",
    langEyebrow: "तुमच्या भाषेत",
    langH2: "संपूर्ण अ‍ॅप तुमची भाषा बोलतं",
    langLede: "आणि जेव्हा तुमच्या राज्याची भाषा तयार होते, आम्ही ती सुरू करतो — तुमच्या भाषेत काळजीपूर्वक तपासून.",
    val1B: "तुमचा डेटा तुमचा.",
    val1S: "विक्री नाही, स्पॅम नाही. खातं केव्हाही एक्सपोर्ट करा.",
    val2B: "जड अ‍ॅप नाही.",
    val2S: "छोटं डाउनलोड, पटकन उघडतं, तुमच्या डेटा पॅकवर हलकं.",
    val3B: "सुरू करणं मोफत.",
    val3S: "अपग्रेड तेव्हाच जेव्हा ते स्पष्ट तुमच्यासाठी कमावतं.",
    val4B: "नियंत्रण तुमच्या हातात.",
    val4S: "भाव, डिलिव्हरी, स्मरणपत्रं — नेहमी तुम्ही ठरवा.",
    nlEyebrow: "न्यूजलेटर",
    nlH2: "दुकानदारांसाठी टिप्स — थेट तुमच्या इनबॉक्समध्ये",
    nlLede: "काही आठवड्यांनी एक छोटं ईमेल — उधारी वसुली, ऑनलाइन दुकान आणि तुमच्या भाषेत नवीन फीचर. केव्हाही अनसब्स्क्राइब करा.",
    nlDoneT: "तुमचा इनबॉक्स बघा",
    nlDoneS: "खात्रीसाठी आम्ही तुम्हाला एक लिंक पाठवली आहे.",
    nlPlaceholder: "तुमचं ईमेल",
    nlAriaEmail: "ईमेल पत्ता",
    nlAriaList: "यादी",
    nlOptCommunity: "दुकानदार",
    nlOptEcosystem: "पार्टनर / वितरक",
    nlSubmit: "सब्स्क्राइब करा",
    nlSending: "पाठवत आहे…",
    nlError: "काहीतरी चुकलं — कृपया पुन्हा प्रयत्न करा.",
    nlNote: "आम्ही तुमचं ईमेल कधीही विकणार नाही. डबल ऑप्ट-इन.",
    finalEyebrow: "आजपासून सुरू करा",
    finalH2: "तुमच्या दुकानाला अशी आठवण द्या जी कधी विसरत नाही.",
    finalLede: "भारतभरातील हजारो काउंटर उधारीवर चालतात. तुमचं Smart Digital Khata वर चालवा — सुरू मोफत, तुमच्या भाषेत, आजच.",
    finalNote: "आधीच सुरू [link]khata.dadashaik.com[/link] वर · कोणत्याही Android फोनवर चालतं",
    getEyebrow: "अ‍ॅप मिळवा",
    getH2: "दोन अ‍ॅप — काउंटरच्या दोन्ही बाजूंसाठी एक एक.",
    getLede: "कोणत्याही Android फोनवर मोफत इन्स्टॉल करा. संगणक नको, Play Store खातेही नको.",
    getCustT: "ग्राहकांसाठी",
    getCustP: "प्रत्येक दुकानातील तुमचं उधार पाहा आणि एका टॅपमध्ये भरा.",
    getCustBtn: "ग्राहक अ‍ॅप मिळवा",
    getShopT: "दुकानदारांसाठी",
    getShopP: "तुमचं खातं, वसुली आणि ऑनलाइन दुकान — तुमच्या खिशात.",
    getShopBtn: "दुकान अ‍ॅप मिळवा",
    getNote: "Android · मोफत · लिंक तुमच्या फोनवर उघडा आणि Install दाबा.",
    footTagline: "प्रत्येक दुकान, आता डिजिटल · Every shop, now digital",
    footBlog: "ब्लॉग",
    footCopy: "© Smart Digital Khata",
  },
  ta: {
    navSignIn: "உள்நுழை",
    navStartFree: "இலவசமாக தொடங்கு",
    langMenuLabel: "மொழியை தேர்வு செய்க",
    heroFlag: "பாரதத்துக்காக உருவானது · நகரங்கள் & கிராமங்கள்",
    heroH1: "உங்கள் கடையின் கணக்கு — இப்போது தொலைபேசியில். மேலும் அதுவே உங்களுக்கு பணத்தை [em]வாங்கித் தருகிறது[/em].",
    heroSub: "டிஜிட்டல் [b]கடன்[/b] கணக்கு, விரைவாக பணம் வசூலிக்கும் WhatsApp நினைவூட்டல்கள், மற்றும் வாடிக்கையாளர்கள் ஆர்டர் செய்யக்கூடிய ஒரு ஆன்லைன் கடை — உங்கள் மொழியில், எந்த தொலைபேசியிலும், தொடங்க இலவசம்.",
    ctaWa: "🟢 WhatsApp-ல் தொடங்கு",
    ctaSignup: "இலவசமாக பதிவு செய்",
    trust2g: "[b]2G[/b]-யிலும் இயங்கும்",
    trustLangs: "[b]10[/b] மொழிகள்",
    trustNoPc: "கணினி தேவையில்லை",
    trustFree: "தொடங்க [b]இலவசம்[/b]",
    phTitle: "இன்றைய கணக்கு",
    phName1: "சீதா தேவி",
    phAmt1: "₹560 பாக்கி",
    phName2: "ரமேஷ் குமார்",
    phAmt2: "₹0 செலுத்தப்பட்டது",
    phBubble: "வணக்கம் சீதா அம்மா 🙏 உங்களிடம் ₹560 பாக்கி உள்ளது. இங்கிருந்து செலுத்துங்கள் 👉",
    phSent: "அனுப்பப்பட்டது ✓✓",
    probEyebrow: "ஒவ்வொரு கடைக்காரருக்கும் தெரிந்த பிரச்சனை",
    probH2: "காகித கணக்கு மறந்துவிடும். வாடிக்கையாளர்களும் மறந்துவிடுவார்கள்.[br]அது [em]உங்கள்[/em] பணம், கதவு வழியாக வெளியேறுகிறது.",
    probLede: "தளர்ந்த தாள்கள், மங்கிய பென்சில், “எவ்வளவு பாக்கி என்று நினைவில்லை.” கடனை கேட்பது சங்கடமாகவும் மெதுவாகவும் இருக்கிறது — எனவே ஒவ்வொரு கடையிலும், ஒவ்வொரு மாதமும் கொஞ்சம் கொஞ்சம் இழக்கப்படுகிறது. Smart Digital Khata அந்த கணக்கை ஒருபோதும் மங்காத நினைவாக மாற்றுகிறது, உங்களுக்காக கேட்கும் ஒரு நினைவூட்டலாகவும்.",
    costEyebrow: "காகித கணக்கின் விலை",
    costH2: "தினமும் சிறு சிறு இழப்புகள்[br]சேர்ந்து உண்மையான பணமாகிவிடும்.",
    costLede: "ஒரு மங்கிய தாள். “மறந்துவிட்ட” ஒரு வாடிக்கையாளர். சங்கடம் என்பதால் ஒருபோதும் அனுப்பப்படாத ஒரு நினைவூட்டல். ஒரு நாளில் பெரிதாகத் தெரியாது — ஆனால் ஆண்டு முழுவதும் சேர்த்தால் கஷ்டப்பட்ட வருமானத்தில் பெரிய ஓட்டை.",
    cost1Big: "~₹14,600",
    cost1Cl: "ஒரு ஆண்டில் இழந்தது, தினமும் வெறும் [b]₹40 கடன்[/b] நழுவினால் — மறந்து, படிக்காமல், அல்லது ஒருபோதும் வசூலிக்காமல்.",
    cost2Big: "3–5 மணி",
    cost2Cl: "வாரத்தில் கையால் கணக்கு கூட்டுவதில் — வாடிக்கையாளர் சேவைக்கோ ஓய்வுக்கோ செல்லக்கூடிய நேரம்.",
    cost3Big: "சங்கடம்",
    cost3Cl: "அண்டை வீட்டாரிடம் நேரில் பணம் கேட்பது. இதனாலேயே எத்தனை கடன்கள் அமைதியாக விடப்படுகின்றன.",
    costIllus: "எடுத்துக்காட்டு மட்டுமே — ஒவ்வொரு கடையும் வேறு. விஷயம் சரியான எண் அல்ல; கையால் செய்யும் வேலை தினமும் அமைதியாக பணத்தையும் நேரத்தையும் கசியவிடுகிறது என்பதே. Smart Digital Khata அந்த கசிவை அடைக்கிறது.",
    pillEyebrow: "உங்களுக்கு கிடைப்பது",
    pillH2: "மூன்று விஷயங்கள், ஒரே எளிய செயலி",
    pill1H3: "உங்களுக்கு பணம் திருப்பித் தரும் டிஜிட்டல் கணக்கு",
    pill1P: "விநாடிகளில் கடனை பதிவு செய்யுங்கள். தானாக WhatsApp & SMS நினைவூட்டல்கள் — வாடிக்கையாளரின் சொந்த மொழியில் — விரைவாக பணம் வாங்கித் தருகின்றன. பணம், UPI அல்லது ஆன்லைன், எல்லாம் ஒரே இடத்தில்.",
    pill1K: "வெறும் கணக்கல்ல, பணமும் →",
    pill2H3: "உங்கள் கடை, இப்போது எல்லோருக்கும் தெரியும்",
    pill2P: "வாடிக்கையாளர்கள் பார்த்து ஆர்டர் செய்யக்கூடிய ஆன்லைன் கடை — பிக்அப், இலவச டெலிவரி அல்லது டெலிவரி கட்டணம் நீங்கள் தேர்வு செய்யலாம். உங்கள் தெருவின் உள்ளூர் வணிகம், எந்த மெட்ரோ க்விக்-காமர்ஸ் செயலியும் அல்ல.",
    pill2K: "புதிய வாடிக்கையாளர்கள், உங்கள் விதிமுறையில் →",
    pill3H3: "உண்மையிலேயே பாரதத்துக்காக உருவானது",
    pill3P: "பத்து மொழிகள் குரலில் படித்துக் காட்டுதலுடன், உங்கள் மொழியில் 1,600 பொருள் பட்டியல், மேலும் 2G-யில் ஆஃப்லைனிலும் இயங்கும் — உங்கள் பாக்கெட்டில் இருக்கும் அன்றாட தொலைபேசியிலேயே. தொடங்க KYC இல்லை.",
    pill3K: "உங்கள் மொழி, உங்கள் தொலைபேசி →",
    bandEyebrow: "நமக்கு உரிய இடம்",
    bandH2: "B & C நகரங்கள் மற்றும் கிராமங்களுக்காக —[br]மெட்ரோக்களுக்கு அல்ல.",
    bandQ: "பிராந்தியம்-முதல், இலகுவானது, உங்களுடையது. கடைக்காரரே தலைவராக இருக்கிறார் — இது கிராண கடை ஏற்கனவே இயங்கும் முறையை மதிக்கும், அமைதியாக அதை வலுப்படுத்தும் ஒரு கருவி. சீர்குலைவு அல்ல. கண்ணியத்துடன் டிஜிட்டல் ஆவது.",
    bandStat1B: "10",
    bandStat1S: "மொழிகள், இதில் இந்தி, வங்காளம், குஜராத்தி, மராத்தி, தமிழ், தெலுங்கு, கன்னடம், மலையாளம் & உருது",
    bandStat2B: "1,600+",
    bandStat2S: "உங்கள் மொழியில் தயார் மளிகை பொருட்கள்",
    bandStat3B: "ஆஃப்லைன்",
    bandStat3S: "பலவீன 2G-யிலும் இயங்கி ஒத்திசைக்கும்",
    bandStat4B: "₹0",
    bandStat4S: "தொடங்க — கார்டு இல்லை, கணினி இல்லை",
    econEyebrow: "பெரிய படம்",
    econH2: "ஒரு கடையை டிஜிட்டல் ஆக்குங்கள், அப்போது ஏதோ[br]பெரியது ஊர் முழுவதற்கும் நடக்கிறது.",
    econLede: "கிராண கடை வெறும் வணிகம் அல்ல — அது ஊரின் நம்பிக்கை, கடன், அன்றாட உயிர்நாடி. அது வலுப்பெறும்போது, முழு அக்கம்பக்கமும் அதனுடன் வளர்கிறது.",
    ec1H3: "பணம் ஊரிலேயே தங்கும்",
    ec1P: "வாடிக்கையாளர் தெரு முனையில் உள்ள கடையில் வாங்குகிறார், இரண்டு ஊர் தொலைவில் உள்ள கிடங்கில் அல்ல. லாபமும் — வாழ்வாதாரமும் — ஊரை விட்டு போகாமல் இங்கேயே தங்கும்.",
    ec2H3: "பணப் புழக்கம் மீண்டும் உயிர்பெறும்",
    ec2P: "விரைவாக வசூலித்த கடன் சிக்கிய முதலீட்டை விடுவிக்கிறது. கடைக்காரர் விரைவில் பொருள் நிரப்பலாம், நியாயமான கடன் தரலாம், குறைவான வருமான மாதங்களிலும் அண்டையாரை சேவிக்கலாம்.",
    ec3H3: "உங்கள் சொந்த மொழியில் கண்ணியம்",
    ec3P: "ஒருபோதும் ஆங்கில மென்பொருளைத் தொடாத கடைக்காரர் இப்போது தமிழ், தெலுங்கு, இந்தி அல்லது உருதுவில் நவீன வணிகம் நடத்துகிறார் — படித்து, கேட்டு, புரிந்துகொள்ளப்படுகிறார். உண்மையிலேயே அனைவரையும் உள்ளடக்கும் டிஜிட்டல் உள்ளடக்கம்.",
    ec4H3: "மூலை கடை நிலைத்திருக்கும்",
    ec4P: "பெரிய சங்கிலிகள் மற்றும் மெட்ரோ செயலிகளுக்கு எதிராக, நம்பகமான உள்ளூர் கிராணவுக்கு அதே நவீன கருவிகள் கிடைக்கின்றன — அவரிடம் ஏற்கனவே உள்ள தொலைபேசியிலேயே. உங்கள் குடும்பம் அறிந்த கடை, நாளைக்கு தயார்.",
    econLine: "வசூலான ஒவ்வொரு நினைவூட்டலும், நிறைவேறிய ஒவ்வொரு ஆர்டரும், ஊரில் தங்கும் ஒவ்வொரு ரூபாயும் — அதுவே கிராம பொருளாதாரத்தை கொஞ்சம் வலுப்படுத்துகிறது, ஒரு நேரத்தில் ஒரு கணக்கு.",
    stepsEyebrow: "இது எப்படி வேலை செய்கிறது",
    stepsH2: "ஐந்து நிமிடத்தில் தயார்",
    step1H3: "உங்கள் மொபைலில் பதிவு செய்யுங்கள்",
    step1P: "உங்கள் தொலைபேசி எண் மற்றும் ஒரு கடவுச்சொல் அல்லது PIN மட்டுமே. பிறகு எண்ணை மாற்றுங்கள், கணக்கை இழக்காமல்.",
    step2H3: "வாடிக்கையாளர்கள் & பொருட்களை சேர்க்கவும்",
    step2P: "தட்டச்சு செய்யுங்கள், அல்லது உங்கள் மொழியில் காட்டப்படும் 1,600 பொருள் பட்டியலில் இருந்து தேர்ந்தெடுங்கள். உங்கள் விலைகளை நீங்களே அமையுங்கள்.",
    step3H3: "பதிவு செய், நினைவூட்டு, விற்பனை செய்",
    step3P: "கடனை குறியுங்கள், WhatsApp-ஐ வசூலிக்க விடுங்கள், உங்கள் கடையிலிருந்து ஆர்டர் எடுங்கள். எல்லாம் ஒரே திரையில் பாருங்கள்.",
    langEyebrow: "உங்கள் மொழியில்",
    langH2: "முழு செயலியும் உங்கள் மொழி பேசுகிறது",
    langLede: "உங்கள் மாநிலத்தின் மொழி தயாராகும்போது, நாங்கள் அதை இயக்குகிறோம் — உங்கள் மொழியில் கவனமாக சரிபார்த்து.",
    val1B: "உங்கள் தரவு உங்களுடையது.",
    val1S: "விற்பனை இல்லை, ஸ்பாம் இல்லை. கணக்கை எப்போது வேண்டுமானாலும் ஏற்றுமதி செய்யுங்கள்.",
    val2B: "கனமான செயலி இல்லை.",
    val2S: "சிறிய பதிவிறக்கம், விரைவில் திறக்கும், உங்கள் டேட்டா பேக்கிற்கு லேசானது.",
    val3B: "தொடங்க இலவசம்.",
    val3S: "இது தெளிவாக உங்களுக்கு சம்பாதிக்கும்போது மட்டுமே அப்கிரேடு செய்யுங்கள்.",
    val4B: "கட்டுப்பாடு உங்கள் கையில்.",
    val4S: "விலை, டெலிவரி, நினைவூட்டல்கள் — எப்போதும் நீங்களே தீர்மானிக்கிறீர்கள்.",
    nlEyebrow: "செய்திமடல்",
    nlH2: "கடைக்காரர்களுக்கான குறிப்புகள் — நேரடியாக உங்கள் இன்பாக்ஸில்",
    nlLede: "சில வாரங்களுக்கு ஒரு சிறிய மின்னஞ்சல் — கடன் வசூல், உங்கள் ஆன்லைன் கடை மற்றும் உங்கள் மொழியில் புதிய அம்சங்கள். எப்போது வேண்டுமானாலும் அன்சப்ஸ்கிரைப் செய்யுங்கள்.",
    nlDoneT: "உங்கள் இன்பாக்ஸை பாருங்கள்",
    nlDoneS: "உறுதிப்படுத்த நாங்கள் உங்களுக்கு ஒரு இணைப்பை அனுப்பியுள்ளோம்.",
    nlPlaceholder: "உங்கள் மின்னஞ்சல்",
    nlAriaEmail: "மின்னஞ்சல் முகவரி",
    nlAriaList: "பட்டியல்",
    nlOptCommunity: "கடைக்காரர்கள்",
    nlOptEcosystem: "பங்குதாரர்கள் / விநியோகஸ்தர்கள்",
    nlSubmit: "சப்ஸ்கிரைப் செய்",
    nlSending: "அனுப்பப்படுகிறது…",
    nlError: "ஏதோ தவறு நடந்தது — தயவுசெய்து மீண்டும் முயற்சிக்கவும்.",
    nlNote: "நாங்கள் உங்கள் மின்னஞ்சலை ஒருபோதும் விற்க மாட்டோம். இரட்டை ஒப்-இன்.",
    finalEyebrow: "இன்றே தொடங்குங்கள்",
    finalH2: "உங்கள் கடைக்கு ஒருபோதும் மறக்காத நினைவைக் கொடுங்கள்.",
    finalLede: "பாரதம் முழுவதும் ஆயிரக்கணக்கான கடைகள் கடனில் இயங்குகின்றன. உங்களுடையதை Smart Digital Khata-வில் இயக்குங்கள் — தொடங்க இலவசம், உங்கள் மொழியில், இன்றே.",
    finalNote: "ஏற்கனவே இயங்குகிறது [link]khata.dadashaik.com[/link]-ல் · எந்த Android தொலைபேசியிலும் இயங்கும்",
    getEyebrow: "செயலியைப் பெறுங்கள்",
    getH2: "இரண்டு செயலிகள் — கடையின் இரு பக்கத்திற்கும் ஒன்று.",
    getLede: "எந்த Android ஃபோனிலும் இலவசமாக நிறுவுங்கள். கம்ப்யூட்டர் வேண்டாம், Play Store கணக்கும் வேண்டாம்.",
    getCustT: "வாடிக்கையாளர்களுக்கு",
    getCustP: "ஒவ்வொரு கடையிலும் உங்கள் கடனைப் பார்த்து ஒரே தட்டில் செலுத்துங்கள்.",
    getCustBtn: "வாடிக்கையாளர் செயலியைப் பெறுங்கள்",
    getShopT: "கடைக்காரர்களுக்கு",
    getShopP: "உங்கள் கணக்கு, வசூல், ஆன்லைன் கடை — உங்கள் பாக்கெட்டில்.",
    getShopBtn: "கடை செயலியைப் பெறுங்கள்",
    getNote: "Android · இலவசம் · லிங்கை உங்கள் ஃபோனில் திறந்து Install-ஐ அழுத்துங்கள்.",
    footTagline: "ஒவ்வொரு கடையும், இப்போது டிஜிட்டல் · Every shop, now digital",
    footBlog: "வலைப்பதிவு",
    footCopy: "© Smart Digital Khata",
  },
  te: {
    navSignIn: "సైన్ ఇన్",
    navStartFree: "ఉచితంగా ప్రారంభించండి",
    langMenuLabel: "భాషను ఎంచుకోండి",
    heroFlag: "భారతదేశం కోసం రూపొందించబడింది · పట్టణాలు & గ్రామాలు",
    heroH1: "మీ దుకాణం ఖాతా — ఇప్పుడు ఫోన్‌లో. అదే మీకు డబ్బు [em]వసూలు చేసి ఇస్తుంది[/em].",
    heroSub: "డిజిటల్ [b]అరువు[/b] ఖాతా, త్వరగా వసూలు చేసే WhatsApp రిమైండర్లు, మరియు కస్టమర్లు ఆర్డర్ చేయగల ఆన్‌లైన్ దుకాణం — మీ భాషలో, ఏ ఫోన్‌లోనైనా, ప్రారంభించడం ఉచితం.",
    ctaWa: "🟢 WhatsApp‌లో ప్రారంభించండి",
    ctaSignup: "ఉచితంగా సైన్ అప్ చేయండి",
    trust2g: "[b]2G[/b]‌లోనూ పనిచేస్తుంది",
    trustLangs: "[b]10[/b] భాషలు",
    trustNoPc: "కంప్యూటర్ అవసరం లేదు",
    trustFree: "ప్రారంభించడం [b]ఉచితం[/b]",
    phTitle: "నేటి లెక్క",
    phName1: "సీత దేవి",
    phAmt1: "₹560 బాకీ",
    phName2: "రమేష్ కుమార్",
    phAmt2: "₹0 జమ",
    phBubble: "నమస్తే సీతమ్మ 🙏 మీకు ₹560 బాకీ ఉంది. ఇక్కడ నుండి చెల్లించండి 👉",
    phSent: "పంపబడింది ✓✓",
    probEyebrow: "ప్రతి దుకాణదారుకూ తెలిసిన సమస్య",
    probH2: "కాగితం ఖాతా మర్చిపోతుంది. కస్టమర్లూ మర్చిపోతారు.[br]అది [em]మీ[/em] డబ్బు, తలుపు నుండి బయటకు వెళ్తుంది.",
    probLede: "వదులైన పేజీలు, మసక పెన్సిల్, “ఎంత బాకీ ఉందో గుర్తు లేదు.” అరువు అడగడం ఇబ్బందిగా, నెమ్మదిగా అనిపిస్తుంది — కాబట్టి ప్రతి కౌంటర్‌లో, ప్రతి నెలా కొంచెం కొంచెం పోతుంది. Smart Digital Khata ఆ ఖాతాను ఎప్పటికీ మసకబారని జ్ఞాపకంగా, మీ తరపున అడిగే రిమైండర్‌గా మారుస్తుంది.",
    costEyebrow: "కాగితం ఖాతా ఖరీదు",
    costH2: "రోజువారీ చిన్న చిన్న నష్టాలు[br]కలిసి నిజమైన డబ్బు అవుతాయి.",
    costLede: "ఒక మసక పేజీ. “మర్చిపోయిన” ఒక కస్టమర్. ఇబ్బంది అనిపించి ఎప్పటికీ పంపని ఒక రిమైండర్. ఒక రోజులో పెద్దదిగా అనిపించదు — కానీ ఏడాదంతా కౌంటర్‌లో లెక్కిస్తే కష్టపడిన సంపాదనలో పెద్ద చిల్లు.",
    cost1Big: "~₹14,600",
    cost1Cl: "ఏడాదిలో పోగొట్టుకున్నది, రోజుకు కేవలం [b]₹40 అరువు[/b] జారిపోతే — మర్చిపోయి, చదవకుండా, లేదా ఎప్పటికీ వసూలు చేయకుండా.",
    cost2Big: "3–5 గంటలు",
    cost2Cl: "వారానికి చేతితో ఖాతా కూడటంలో — కస్టమర్ సేవకో విశ్రాంతికో ఉపయోగపడే సమయం.",
    cost3Big: "ఇబ్బంది",
    cost3Cl: "పొరుగువారిని ముఖాముఖి డబ్బు అడగడం. అందుకే ఎన్నో అరువులు నిశ్శబ్దంగా వదిలేయబడతాయి.",
    costIllus: "ఉదాహరణ మాత్రమే — ప్రతి దుకాణం వేరు. విషయం ఖచ్చితమైన సంఖ్య కాదు; చేతి పని రోజూ నిశ్శబ్దంగా డబ్బునూ సమయాన్నీ కారుస్తుంది అనేదే. Smart Digital Khata ఆ లీకును ఆపుతుంది.",
    pillEyebrow: "మీకు ఏమి లభిస్తుంది",
    pillH2: "మూడు విషయాలు, ఒకే సులభమైన యాప్",
    pill1H3: "మీకు తిరిగి ఇచ్చే డిజిటల్ ఖాతా",
    pill1P: "సెకన్లలో అరువు రాయండి. ఆటోమేటిక్ WhatsApp & SMS రిమైండర్లు — కస్టమర్ సొంత భాషలో — త్వరగా డబ్బు తెప్పిస్తాయి. నగదు, UPI లేదా ఆన్‌లైన్, అన్నీ ఒకే చోట.",
    pill1K: "కేవలం లెక్క కాదు, డబ్బు కూడా →",
    pill2H3: "మీ దుకాణం, ఇప్పుడు అందరికీ కనిపిస్తుంది",
    pill2P: "కస్టమర్లు చూసి ఆర్డర్ చేయగల ఆన్‌లైన్ దుకాణం — పికప్, ఉచిత డెలివరీ లేదా డెలివరీ ఛార్జ్ మీరు ఎంచుకోండి. మీ వీధి స్థానిక వ్యాపారం, ఏ మెట్రో క్విక్-కామర్స్ యాప్ కాదు.",
    pill2K: "కొత్త కస్టమర్లు, మీ షరతులపై →",
    pill3H3: "నిజంగా భారతదేశం కోసం రూపొందించబడింది",
    pill3P: "పది భాషలు గొంతుతో చదివి వినిపించడంతో, మీ భాషలో 1,600 వస్తువుల జాబితా, మరియు 2G‌లో ఆఫ్‌లైన్‌లోనూ పనిచేస్తుంది — మీ జేబులో ఉన్న రోజువారీ ఫోన్‌లోనే. ప్రారంభించడానికి KYC లేదు.",
    pill3K: "మీ భాష, మీ ఫోన్ →",
    bandEyebrow: "మా స్థానం ఎక్కడ",
    bandH2: "B & C పట్టణాలు, గ్రామాల కోసం —[br]మెట్రోల కోసం కాదు.",
    bandQ: "ప్రాంతీయం-మొదట, తేలికైనది, మీ సొంతం. దుకాణదారే యజమానిగా ఉంటాడు — ఇది కిరాణా ఇప్పటికే పనిచేసే విధానాన్ని గౌరవిస్తూ నిశ్శబ్దంగా బలోపేతం చేసే సాధనం. విధ్వంసం కాదు. గౌరవంతో డిజిటల్ కావడం.",
    bandStat1B: "10",
    bandStat1S: "భాషలు, వీటిలో హిందీ, బెంగాలీ, గుజరాతీ, మరాఠీ, తమిళం, తెలుగు, కన్నడ, మలయాళం & ఉర్దూ",
    bandStat2B: "1,600+",
    bandStat2S: "మీ భాషలో సిద్ధంగా ఉన్న కిరాణా వస్తువులు",
    bandStat3B: "ఆఫ్‌లైన్",
    bandStat3S: "బలహీన 2G‌లోనూ పనిచేసి సింక్ అవుతుంది",
    bandStat4B: "₹0",
    bandStat4S: "ప్రారంభించడానికి — కార్డు లేదు, కంప్యూటర్ లేదు",
    econEyebrow: "పెద్ద చిత్రం",
    econH2: "ఒక దుకాణాన్ని డిజిటల్ చేయండి, అప్పుడు ఏదో[br]పెద్దది ఊరు మొత్తానికి జరుగుతుంది.",
    econLede: "కిరాణా దుకాణం కేవలం వ్యాపారం కాదు — అది ఊరి నమ్మకం, అరువు, రోజువారీ ప్రాణాధారం. అది బలపడినప్పుడు, మొత్తం పరిసరం దానితో పాటు ఎదుగుతుంది.",
    ec1H3: "డబ్బు ఊరిలోనే ఉంటుంది",
    ec1P: "కస్టమర్ వీధి చివరి దుకాణంలో కొంటాడు, రెండు ఊర్ల దూరంలోని గోడౌన్‌లో కాదు. లాభం — జీవనోపాధి — ఊరు వదిలి పోకుండా ఇక్కడే ఉంటుంది.",
    ec2H3: "నగదు ప్రవాహం మళ్లీ ప్రాణం పోసుకుంటుంది",
    ec2P: "త్వరగా వసూలైన అరువు ఇరుక్కుపోయిన మూలధనాన్ని విడిపిస్తుంది. దుకాణదారు త్వరగా సరుకు నింపవచ్చు, న్యాయమైన అరువు ఇవ్వవచ్చు, తక్కువ సంపాదన నెలల్లోనూ పొరుగువారికి సేవ చేయవచ్చు.",
    ec3H3: "మీ సొంత భాషలో గౌరవం",
    ec3P: "ఎప్పుడూ ఇంగ్లిష్ సాఫ్ట్‌వేర్ ముట్టుకోని దుకాణదారు ఇప్పుడు తమిళం, తెలుగు, హిందీ లేదా ఉర్దూలో ఆధునిక వ్యాపారం నడుపుతున్నాడు — చదివి, విని, అర్థం చేసుకోబడతాడు. నిజంగా అందరినీ కలుపుకునే డిజిటల్ చేరిక.",
    ec4H3: "మూల దుకాణం నిలదొక్కుకుంటుంది",
    ec4P: "పెద్ద చైన్‌లు, మెట్రో యాప్‌లకు వ్యతిరేకంగా, నమ్మకమైన స్థానిక కిరాణాకు అదే ఆధునిక సాధనాలు లభిస్తాయి — తన సొంత ఫోన్‌లోనే. మీ కుటుంబానికి తెలిసిన దుకాణం, రేపటికి సిద్ధం.",
    econLine: "వసూలైన ప్రతి రిమైండర్, పూర్తయిన ప్రతి ఆర్డర్, ఊరిలో ఉండే ప్రతి రూపాయి — అదే గ్రామ ఆర్థికవ్యవస్థను కొంచెం బలోపేతం చేస్తుంది, ఒకసారి ఒక ఖాతా.",
    stepsEyebrow: "ఇది ఎలా పనిచేస్తుంది",
    stepsH2: "ఐదు నిమిషాల్లో సిద్ధం",
    step1H3: "మీ మొబైల్‌తో సైన్ అప్ చేయండి",
    step1P: "కేవలం మీ ఫోన్ నంబర్ మరియు ఒక పాస్‌వర్డ్ లేదా PIN. తర్వాత నంబర్ మార్చండి, ఖాతా కోల్పోకుండా.",
    step2H3: "కస్టమర్లు & వస్తువులు జోడించండి",
    step2P: "టైప్ చేయండి, లేదా మీ భాషలో కనిపించే 1,600 వస్తువుల జాబితా నుండి ఎంచుకోండి. మీ ధరలు మీరే నిర్ణయించండి.",
    step3H3: "రాయండి, గుర్తు చేయండి, అమ్మండి",
    step3P: "అరువు నమోదు చేయండి, WhatsApp‌ను వసూలు చేయనివ్వండి, మీ దుకాణం నుండి ఆర్డర్లు తీసుకోండి. అన్నీ ఒకే స్క్రీన్‌లో చూడండి.",
    langEyebrow: "మీ భాషలో",
    langH2: "మొత్తం యాప్ మీ భాష మాట్లాడుతుంది",
    langLede: "మీ రాష్ట్ర భాష సిద్ధమైనప్పుడు, మేము దాన్ని ఆన్ చేస్తాము — మీ భాషలో జాగ్రత్తగా సరిచూసి.",
    val1B: "మీ డేటా మీది.",
    val1S: "అమ్మకం లేదు, స్పామ్ లేదు. ఖాతా ఎప్పుడైనా ఎగుమతి చేయండి.",
    val2B: "బరువైన యాప్ కాదు.",
    val2S: "చిన్న డౌన్‌లోడ్, వేగంగా తెరుచుకుంటుంది, మీ డేటా ప్యాక్‌కు తేలిక.",
    val3B: "ప్రారంభించడం ఉచితం.",
    val3S: "అది స్పష్టంగా మీకు సంపాదించినప్పుడే అప్‌గ్రేడ్ చేయండి.",
    val4B: "నియంత్రణ మీ చేతిలో.",
    val4S: "ధరలు, డెలివరీ, రిమైండర్లు — ఎప్పుడూ మీరే నిర్ణయిస్తారు.",
    nlEyebrow: "న్యూస్‌లెటర్",
    nlH2: "దుకాణదారుల కోసం చిట్కాలు — నేరుగా మీ ఇన్‌బాక్స్‌కు",
    nlLede: "కొన్ని వారాలకు ఒక చిన్న ఇమెయిల్ — అరువు వసూలు, మీ ఆన్‌లైన్ దుకాణం మరియు మీ భాషలో కొత్త ఫీచర్లు. ఎప్పుడైనా అన్‌సబ్‌స్క్రైబ్ చేయండి.",
    nlDoneT: "మీ ఇన్‌బాక్స్ చూడండి",
    nlDoneS: "నిర్ధారించడానికి మేము మీకు ఒక లింక్ పంపాము.",
    nlPlaceholder: "మీ ఇమెయిల్",
    nlAriaEmail: "ఇమెయిల్ చిరునామా",
    nlAriaList: "జాబితా",
    nlOptCommunity: "దుకాణదారులు",
    nlOptEcosystem: "భాగస్వాములు / పంపిణీదారులు",
    nlSubmit: "సబ్‌స్క్రైబ్ చేయండి",
    nlSending: "పంపుతోంది…",
    nlError: "ఏదో తప్పు జరిగింది — దయచేసి మళ్లీ ప్రయత్నించండి.",
    nlNote: "మేము మీ ఇమెయిల్‌ను ఎప్పటికీ అమ్మము. డబుల్ ఆప్ట్-ఇన్.",
    finalEyebrow: "ఈరోజే ప్రారంభించండి",
    finalH2: "మీ దుకాణానికి ఎప్పటికీ మర్చిపోని జ్ఞాపకాన్ని ఇవ్వండి.",
    finalLede: "భారతదేశం అంతటా వేలాది కౌంటర్లు అరువుపై నడుస్తాయి. మీది Smart Digital Khata‌పై నడపండి — ప్రారంభం ఉచితం, మీ భాషలో, ఈరోజే.",
    finalNote: "ఇప్పటికే నడుస్తోంది [link]khata.dadashaik.com[/link]‌లో · ఏ Android ఫోన్‌లోనైనా పనిచేస్తుంది",
    getEyebrow: "యాప్ పొందండి",
    getH2: "రెండు యాప్‌లు — కౌంటర్ రెండు వైపులకు ఒక్కొక్కటి.",
    getLede: "ఏ Android ఫోన్‌లోనైనా ఉచితంగా ఇన్‌స్టాల్ చేయండి. కంప్యూటర్ అవసరం లేదు, Play Store ఖాతా కూడా అవసరం లేదు.",
    getCustT: "వినియోగదారుల కోసం",
    getCustP: "ప్రతి దుకాణంలో మీ అప్పును చూసి ఒక్క ట్యాప్‌తో చెల్లించండి.",
    getCustBtn: "కస్టమర్ యాప్ పొందండి",
    getShopT: "దుకాణదారుల కోసం",
    getShopP: "మీ ఖాతా, వసూలు మరియు ఆన్‌లైన్ దుకాణం — మీ జేబులో.",
    getShopBtn: "షాప్ యాప్ పొందండి",
    getNote: "Android · ఉచితం · లింక్‌ను మీ ఫోన్‌లో తెరిచి Install నొక్కండి.",
    footTagline: "ప్రతి దుకాణం, ఇప్పుడు డిజిటల్ · Every shop, now digital",
    footBlog: "బ్లాగ్",
    footCopy: "© Smart Digital Khata",
  },
  kn: {
    navSignIn: "ಸೈನ್ ಇನ್",
    navStartFree: "ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ",
    langMenuLabel: "ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",
    heroFlag: "ಭಾರತಕ್ಕಾಗಿ ರಚಿಸಲಾಗಿದೆ · ಪಟ್ಟಣಗಳು & ಹಳ್ಳಿಗಳು",
    heroH1: "ನಿಮ್ಮ ಅಂಗಡಿಯ ಖಾತೆ — ಈಗ ಫೋನ್‌ನಲ್ಲಿ. ಮತ್ತು ಅದೇ ನಿಮಗೆ ಹಣವನ್ನು [em]ವಸೂಲಿ ಮಾಡಿಕೊಡುತ್ತದೆ[/em].",
    heroSub: "ಡಿಜಿಟಲ್ [b]ಸಾಲ[/b] ಖಾತೆ, ಬೇಗ ವಸೂಲಿ ಮಾಡುವ WhatsApp ಜ್ಞಾಪನೆಗಳು, ಮತ್ತು ಗ್ರಾಹಕರು ಆರ್ಡರ್ ಮಾಡಬಹುದಾದ ಒಂದು ಆನ್‌ಲೈನ್ ಅಂಗಡಿ — ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ, ಯಾವುದೇ ಫೋನ್‌ನಲ್ಲಿ, ಆರಂಭಿಸಲು ಉಚಿತ.",
    ctaWa: "🟢 WhatsApp‌ನಲ್ಲಿ ಪ್ರಾರಂಭಿಸಿ",
    ctaSignup: "ಉಚಿತವಾಗಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    trust2g: "[b]2G[/b]‌ನಲ್ಲೂ ನಡೆಯುತ್ತದೆ",
    trustLangs: "[b]10[/b] ಭಾಷೆಗಳು",
    trustNoPc: "ಕಂಪ್ಯೂಟರ್ ಬೇಕಿಲ್ಲ",
    trustFree: "ಆರಂಭಿಸಲು [b]ಉಚಿತ[/b]",
    phTitle: "ಇಂದಿನ ಲೆಕ್ಕ",
    phName1: "ಸೀತಾ ದೇವಿ",
    phAmt1: "₹560 ಬಾಕಿ",
    phName2: "ರಮೇಶ್ ಕುಮಾರ್",
    phAmt2: "₹0 ಜಮಾ",
    phBubble: "ನಮಸ್ಕಾರ ಸೀತಮ್ಮ 🙏 ನಿಮ್ಮ ₹560 ಬಾಕಿ ಇದೆ. ಇಲ್ಲಿಂದ ಪಾವತಿಸಿ 👉",
    phSent: "ಕಳುಹಿಸಲಾಗಿದೆ ✓✓",
    probEyebrow: "ಪ್ರತಿ ಅಂಗಡಿಯವನಿಗೂ ಗೊತ್ತಿರುವ ಸಮಸ್ಯೆ",
    probH2: "ಕಾಗದದ ಲೆಕ್ಕ ಮರೆಯುತ್ತದೆ. ಗ್ರಾಹಕರೂ ಮರೆಯುತ್ತಾರೆ.[br]ಅದು [em]ನಿಮ್ಮ[/em] ಹಣ, ಬಾಗಿಲಿನಿಂದ ಹೊರ ಹೋಗುತ್ತದೆ.",
    probLede: "ಸಡಿಲ ಹಾಳೆಗಳು, ಮಸುಕಾದ ಪೆನ್ಸಿಲ್, “ಎಷ್ಟು ಬಾಕಿ ಇತ್ತೋ ನೆನಪಿಲ್ಲ.” ಸಾಲ ಕೇಳುವುದು ಮುಜುಗರ ಮತ್ತು ನಿಧಾನ — ಹಾಗಾಗಿ ಪ್ರತಿ ಅಂಗಡಿಯಲ್ಲೂ, ಪ್ರತಿ ತಿಂಗಳೂ ಸ್ವಲ್ಪ ಸ್ವಲ್ಪ ನಷ್ಟವಾಗುತ್ತದೆ. Smart Digital Khata ಆ ಲೆಕ್ಕವನ್ನು ಎಂದೂ ಮಸುಕಾಗದ ನೆನಪಾಗಿಸುತ್ತದೆ, ನಿಮ್ಮ ಪರವಾಗಿ ಕೇಳುವ ಜ್ಞಾಪನೆಯಾಗಿಸುತ್ತದೆ.",
    costEyebrow: "ಕಾಗದದ ಲೆಕ್ಕದ ಬೆಲೆ",
    costH2: "ಪ್ರತಿ ದಿನದ ಸಣ್ಣ ಸಣ್ಣ ನಷ್ಟಗಳು[br]ಸೇರಿ ನಿಜವಾದ ಹಣವಾಗುತ್ತವೆ.",
    costLede: "ಒಂದು ಮಸುಕಾದ ಹಾಳೆ. “ಮರೆತುಬಿಟ್ಟ” ಒಬ್ಬ ಗ್ರಾಹಕ. ಮುಜುಗರವೆಂದು ಎಂದೂ ಕಳುಹಿಸದ ಒಂದು ಜ್ಞಾಪನೆ. ಒಂದು ದಿನದಲ್ಲಿ ದೊಡ್ಡದೆನಿಸದು — ಆದರೆ ವರ್ಷವಿಡೀ ಅಂಗಡಿಯ ಲೆಕ್ಕ ಹಾಕಿದರೆ ಕಷ್ಟಪಟ್ಟ ಆದಾಯದಲ್ಲಿ ದೊಡ್ಡ ರಂಧ್ರ.",
    cost1Big: "~₹14,600",
    cost1Cl: "ವರ್ಷದಲ್ಲಿ ಕಳೆದುಕೊಂಡದ್ದು, ದಿನಕ್ಕೆ ಕೇವಲ [b]₹40 ಸಾಲ[/b] ಜಾರಿಹೋದರೆ — ಮರೆತು, ಓದದೆ, ಅಥವಾ ಎಂದೂ ವಸೂಲಿ ಮಾಡದೆ.",
    cost2Big: "3–5 ಗಂಟೆ",
    cost2Cl: "ವಾರಕ್ಕೆ ಕೈಯಿಂದ ಲೆಕ್ಕ ಕೂಡಿಸುವುದರಲ್ಲಿ — ಗ್ರಾಹಕ ಸೇವೆಗೋ ವಿಶ್ರಾಂತಿಗೋ ಬಳಸಬಹುದಾದ ಸಮಯ.",
    cost3Big: "ಮುಜುಗರ",
    cost3Cl: "ನೆರೆಯವರ ಬಳಿ ಮುಖಾಮುಖಿ ಹಣ ಕೇಳುವುದು. ಇದೇ ಕಾರಣಕ್ಕೆ ಎಷ್ಟೋ ಸಾಲಗಳು ಮೌನವಾಗಿ ಬಿಟ್ಟುಬಿಡಲಾಗುತ್ತವೆ.",
    costIllus: "ಉದಾಹರಣೆ ಮಾತ್ರ — ಪ್ರತಿ ಅಂಗಡಿ ಬೇರೆ. ವಿಷಯ ನಿಖರ ಸಂಖ್ಯೆಯಲ್ಲ; ಕೈ ಕೆಲಸ ಪ್ರತಿ ದಿನ ಮೌನವಾಗಿ ಹಣ ಮತ್ತು ಸಮಯ ಸೋರಿಸುತ್ತದೆ ಎಂಬುದೇ. Smart Digital Khata ಆ ಸೋರಿಕೆಯನ್ನು ತಡೆಯುತ್ತದೆ.",
    pillEyebrow: "ನಿಮಗೆ ಏನು ಸಿಗುತ್ತದೆ",
    pillH2: "ಮೂರು ವಿಷಯ, ಒಂದೇ ಸುಲಭ ಆ್ಯಪ್",
    pill1H3: "ನಿಮಗೆ ಮರಳಿ ಕೊಡುವ ಡಿಜಿಟಲ್ ಖಾತೆ",
    pill1P: "ಕ್ಷಣಗಳಲ್ಲಿ ಸಾಲ ಬರೆಯಿರಿ. ಸ್ವಯಂಚಾಲಿತ WhatsApp & SMS ಜ್ಞಾಪನೆಗಳು — ಗ್ರಾಹಕನ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ — ಬೇಗ ಹಣ ತಂದುಕೊಡುತ್ತವೆ. ನಗದು, UPI ಅಥವಾ ಆನ್‌ಲೈನ್, ಎಲ್ಲವೂ ಒಂದೇ ಕಡೆ.",
    pill1K: "ಕೇವಲ ಲೆಕ್ಕವಲ್ಲ, ಹಣವೂ →",
    pill2H3: "ನಿಮ್ಮ ಅಂಗಡಿ, ಈಗ ಎಲ್ಲರಿಗೂ ಕಾಣುತ್ತದೆ",
    pill2P: "ಗ್ರಾಹಕರು ನೋಡಿ ಆರ್ಡರ್ ಮಾಡಬಹುದಾದ ಆನ್‌ಲೈನ್ ಅಂಗಡಿ — ಪಿಕಪ್, ಉಚಿತ ಡೆಲಿವರಿ ಅಥವಾ ಡೆಲಿವರಿ ಶುಲ್ಕ ನೀವು ಆಯ್ಕೆಮಾಡಿ. ನಿಮ್ಮ ಬೀದಿಯ ಸ್ಥಳೀಯ ವ್ಯಾಪಾರ, ಯಾವುದೇ ಮೆಟ್ರೊ ಕ್ವಿಕ್-ಕಾಮರ್ಸ್ ಆ್ಯಪ್ ಅಲ್ಲ.",
    pill2K: "ಹೊಸ ಗ್ರಾಹಕರು, ನಿಮ್ಮ ಷರತ್ತಿನಲ್ಲಿ →",
    pill3H3: "ನಿಜವಾಗಿ ಭಾರತಕ್ಕಾಗಿ ರಚಿಸಲಾಗಿದೆ",
    pill3P: "ಹತ್ತು ಭಾಷೆಗಳು ಧ್ವನಿಯಲ್ಲಿ ಓದಿ ಹೇಳುವುದರೊಂದಿಗೆ, ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ 1,600 ವಸ್ತುಗಳ ಪಟ್ಟಿ, ಮತ್ತು 2G‌ನಲ್ಲಿ ಆಫ್‌ಲೈನ್‌ನಲ್ಲೂ ನಡೆಯುತ್ತದೆ — ನಿಮ್ಮ ಜೇಬಿನಲ್ಲಿರುವ ನಿತ್ಯದ ಫೋನ್‌ನಲ್ಲೇ. ಆರಂಭಿಸಲು KYC ಇಲ್ಲ.",
    pill3K: "ನಿಮ್ಮ ಭಾಷೆ, ನಿಮ್ಮ ಫೋನ್ →",
    bandEyebrow: "ನಮ್ಮ ಸ್ಥಾನ ಎಲ್ಲಿ",
    bandH2: "B & C ಪಟ್ಟಣಗಳು ಮತ್ತು ಹಳ್ಳಿಗಳಿಗಾಗಿ —[br]ಮೆಟ್ರೊಗಳಿಗಾಗಿ ಅಲ್ಲ.",
    bandQ: "ಪ್ರಾದೇಶಿಕ-ಮೊದಲು, ಹಗುರ, ಮತ್ತು ನಿಮ್ಮದೇ. ಅಂಗಡಿಯವನೇ ಮಾಲೀಕನಾಗಿ ಉಳಿಯುತ್ತಾನೆ — ಇದು ಕಿರಾಣಿ ಈಗಾಗಲೇ ನಡೆಯುವ ರೀತಿಯನ್ನು ಗೌರವಿಸುತ್ತ ಮೌನವಾಗಿ ಬಲಪಡಿಸುವ ಸಾಧನ. ವಿಘಟನೆ ಅಲ್ಲ. ಗೌರವದೊಂದಿಗೆ ಡಿಜಿಟಲ್ ಆಗುವುದು.",
    bandStat1B: "10",
    bandStat1S: "ಭಾಷೆಗಳು, ಇವುಗಳಲ್ಲಿ ಹಿಂದಿ, ಬಂಗಾಳಿ, ಗುಜರಾತಿ, ಮರಾಠಿ, ತಮಿಳು, ತೆಲುಗು, ಕನ್ನಡ, ಮಲಯಾಳಂ & ಉರ್ದು",
    bandStat2B: "1,600+",
    bandStat2S: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಸಿದ್ಧ ದಿನಸಿ ವಸ್ತುಗಳು",
    bandStat3B: "ಆಫ್‌ಲೈನ್",
    bandStat3S: "ದುರ್ಬಲ 2G‌ನಲ್ಲೂ ನಡೆದು ಸಿಂಕ್ ಆಗುತ್ತದೆ",
    bandStat4B: "₹0",
    bandStat4S: "ಆರಂಭಿಸಲು — ಕಾರ್ಡ್ ಇಲ್ಲ, ಕಂಪ್ಯೂಟರ್ ಇಲ್ಲ",
    econEyebrow: "ದೊಡ್ಡ ಚಿತ್ರ",
    econH2: "ಒಂದು ಅಂಗಡಿಯನ್ನು ಡಿಜಿಟಲ್ ಮಾಡಿ, ಆಗ ಏನೋ[br]ದೊಡ್ಡದು ಇಡೀ ಊರಿಗೆ ಆಗುತ್ತದೆ.",
    econLede: "ಕಿರಾಣಿ ಅಂಗಡಿ ಕೇವಲ ವ್ಯಾಪಾರವಲ್ಲ — ಅದು ಊರಿನ ನಂಬಿಕೆ, ಸಾಲ, ನಿತ್ಯದ ಜೀವನಾಡಿ. ಅದು ಬಲಗೊಂಡಾಗ, ಇಡೀ ನೆರೆಹೊರೆ ಅದರೊಂದಿಗೆ ಬೆಳೆಯುತ್ತದೆ.",
    ec1H3: "ಹಣ ಊರಿನಲ್ಲೇ ಉಳಿಯುತ್ತದೆ",
    ec1P: "ಗ್ರಾಹಕ ಬೀದಿಯ ಕೊನೆಯ ಅಂಗಡಿಯಿಂದ ಕೊಳ್ಳುತ್ತಾನೆ, ಎರಡು ಊರು ದೂರದ ಗೋದಾಮಿನಿಂದ ಅಲ್ಲ. ಲಾಭ — ಜೀವನೋಪಾಯ — ಊರು ಬಿಟ್ಟು ಹೋಗದೆ ಇಲ್ಲೇ ಉಳಿಯುತ್ತದೆ.",
    ec2H3: "ನಗದು ಹರಿವು ಮತ್ತೆ ಜೀವ ಪಡೆಯುತ್ತದೆ",
    ec2P: "ಬೇಗ ವಸೂಲಾದ ಸಾಲ ಸಿಕ್ಕಿಬಿದ್ದ ಬಂಡವಾಳವನ್ನು ಬಿಡಿಸುತ್ತದೆ. ಅಂಗಡಿಯವನು ಬೇಗ ಸರಕು ತುಂಬಬಹುದು, ನ್ಯಾಯವಾದ ಸಾಲ ಕೊಡಬಹುದು, ಕಡಿಮೆ ಆದಾಯದ ತಿಂಗಳಲ್ಲೂ ನೆರೆಯವರಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸಬಹುದು.",
    ec3H3: "ನಿಮ್ಮ ಸ್ವಂತ ಭಾಷೆಯಲ್ಲಿ ಗೌರವ",
    ec3P: "ಎಂದೂ ಇಂಗ್ಲಿಷ್ ಸಾಫ್ಟ್‌ವೇರ್ ಮುಟ್ಟದ ಅಂಗಡಿಯವನು ಈಗ ತಮಿಳು, ತೆಲುಗು, ಹಿಂದಿ ಅಥವಾ ಉರ್ದುವಿನಲ್ಲಿ ಆಧುನಿಕ ವ್ಯಾಪಾರ ನಡೆಸುತ್ತಾನೆ — ಓದಿ, ಕೇಳಿ, ಅರ್ಥವಾಗುತ್ತಾನೆ. ನಿಜವಾಗಿ ಎಲ್ಲರನ್ನೂ ಒಳಗೊಳ್ಳುವ ಡಿಜಿಟಲ್ ಸೇರ್ಪಡೆ.",
    ec4H3: "ಮೂಲೆ ಅಂಗಡಿ ಉಳಿಯುತ್ತದೆ",
    ec4P: "ದೊಡ್ಡ ಸರಪಳಿಗಳು ಮತ್ತು ಮೆಟ್ರೊ ಆ್ಯಪ್‌ಗಳ ಎದುರು, ನಂಬಿಕಸ್ಥ ಸ್ಥಳೀಯ ಕಿರಾಣಿಗೆ ಅದೇ ಆಧುನಿಕ ಸಾಧನಗಳು ಸಿಗುತ್ತವೆ — ತನ್ನ ಸ್ವಂತ ಫೋನ್‌ನಲ್ಲೇ. ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕೆ ಗೊತ್ತಿರುವ ಅಂಗಡಿ, ನಾಳೆಗೆ ಸಿದ್ಧ.",
    econLine: "ವಸೂಲಾದ ಪ್ರತಿ ಜ್ಞಾಪನೆ, ಪೂರೈಸಿದ ಪ್ರತಿ ಆರ್ಡರ್, ಊರಿನಲ್ಲಿ ಉಳಿಯುವ ಪ್ರತಿ ರೂಪಾಯಿ — ಅದೇ ಹಳ್ಳಿಯ ಆರ್ಥಿಕತೆಯನ್ನು ಸ್ವಲ್ಪ ಬಲಪಡಿಸುತ್ತದೆ, ಒಂದು ಖಾತೆ ಒಂದು ಬಾರಿ.",
    stepsEyebrow: "ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    stepsH2: "ಐದು ನಿಮಿಷದಲ್ಲಿ ಸಿದ್ಧ",
    step1H3: "ನಿಮ್ಮ ಮೊಬೈಲ್‌ನಿಂದ ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    step1P: "ಕೇವಲ ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ಮತ್ತು ಒಂದು ಪಾಸ್‌ವರ್ಡ್ ಅಥವಾ PIN. ನಂತರ ನಂಬರ್ ಬದಲಿಸಿ, ಖಾತೆ ಕಳೆದುಕೊಳ್ಳದೆ.",
    step2H3: "ಗ್ರಾಹಕರು & ವಸ್ತುಗಳನ್ನು ಸೇರಿಸಿ",
    step2P: "ಟೈಪ್ ಮಾಡಿ, ಅಥವಾ ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಕಾಣುವ 1,600 ವಸ್ತುಗಳ ಪಟ್ಟಿಯಿಂದ ಆಯ್ಕೆಮಾಡಿ. ನಿಮ್ಮ ಬೆಲೆಗಳನ್ನು ನೀವೇ ನಿಗದಿಪಡಿಸಿ.",
    step3H3: "ಬರೆಯಿರಿ, ನೆನಪಿಸಿ, ಮಾರಿ",
    step3P: "ಸಾಲ ದಾಖಲಿಸಿ, WhatsApp‌ಗೆ ವಸೂಲಿ ಮಾಡಲು ಬಿಡಿ, ನಿಮ್ಮ ಅಂಗಡಿಯಿಂದ ಆರ್ಡರ್ ತೆಗೆದುಕೊಳ್ಳಿ. ಎಲ್ಲವನ್ನೂ ಒಂದೇ ಪರದೆಯಲ್ಲಿ ನೋಡಿ.",
    langEyebrow: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ",
    langH2: "ಇಡೀ ಆ್ಯಪ್ ನಿಮ್ಮ ಭಾಷೆ ಮಾತನಾಡುತ್ತದೆ",
    langLede: "ಮತ್ತು ನಿಮ್ಮ ರಾಜ್ಯದ ಭಾಷೆ ಸಿದ್ಧವಾದಾಗ, ನಾವು ಅದನ್ನು ಆನ್ ಮಾಡುತ್ತೇವೆ — ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಎಚ್ಚರಿಕೆಯಿಂದ ಪರಿಶೀಲಿಸಿ.",
    val1B: "ನಿಮ್ಮ ಡೇಟಾ ನಿಮ್ಮದು.",
    val1S: "ಮಾರಾಟ ಇಲ್ಲ, ಸ್ಪ್ಯಾಮ್ ಇಲ್ಲ. ಖಾತೆಯನ್ನು ಯಾವಾಗ ಬೇಕಾದರೂ ಎಕ್ಸ್‌ಪೋರ್ಟ್ ಮಾಡಿ.",
    val2B: "ಭಾರೀ ಆ್ಯಪ್ ಅಲ್ಲ.",
    val2S: "ಸಣ್ಣ ಡೌನ್‌ಲೋಡ್, ಬೇಗ ತೆರೆಯುತ್ತದೆ, ನಿಮ್ಮ ಡೇಟಾ ಪ್ಯಾಕ್‌ಗೆ ಹಗುರ.",
    val3B: "ಆರಂಭಿಸಲು ಉಚಿತ.",
    val3S: "ಇದು ಸ್ಪಷ್ಟವಾಗಿ ನಿಮಗೆ ಗಳಿಸಿದಾಗ ಮಾತ್ರ ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ.",
    val4B: "ನಿಯಂತ್ರಣ ನಿಮ್ಮ ಕೈಯಲ್ಲಿ.",
    val4S: "ಬೆಲೆ, ಡೆಲಿವರಿ, ಜ್ಞಾಪನೆ — ಯಾವಾಗಲೂ ನೀವೇ ನಿರ್ಧರಿಸುತ್ತೀರಿ.",
    nlEyebrow: "ನ್ಯೂಸ್‌ಲೆಟರ್",
    nlH2: "ಅಂಗಡಿಯವರಿಗೆ ಸಲಹೆಗಳು — ನೇರವಾಗಿ ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್‌ಗೆ",
    nlLede: "ಕೆಲವು ವಾರಗಳಿಗೊಮ್ಮೆ ಒಂದು ಸಣ್ಣ ಇಮೇಲ್ — ಸಾಲ ವಸೂಲಿ, ನಿಮ್ಮ ಆನ್‌ಲೈನ್ ಅಂಗಡಿ ಮತ್ತು ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಹೊಸ ಫೀಚರ್‌ಗಳು. ಯಾವಾಗ ಬೇಕಾದರೂ ಅನ್‌ಸಬ್‌ಸ್ಕ್ರೈಬ್ ಮಾಡಿ.",
    nlDoneT: "ನಿಮ್ಮ ಇನ್‌ಬಾಕ್ಸ್ ನೋಡಿ",
    nlDoneS: "ದೃಢೀಕರಿಸಲು ನಾವು ನಿಮಗೆ ಒಂದು ಲಿಂಕ್ ಕಳುಹಿಸಿದ್ದೇವೆ.",
    nlPlaceholder: "ನಿಮ್ಮ ಇಮೇಲ್",
    nlAriaEmail: "ಇಮೇಲ್ ವಿಳಾಸ",
    nlAriaList: "ಪಟ್ಟಿ",
    nlOptCommunity: "ಅಂಗಡಿಯವರು",
    nlOptEcosystem: "ಪಾಲುದಾರರು / ವಿತರಕರು",
    nlSubmit: "ಸಬ್‌ಸ್ಕ್ರೈಬ್ ಮಾಡಿ",
    nlSending: "ಕಳುಹಿಸಲಾಗುತ್ತಿದೆ…",
    nlError: "ಏನೋ ತಪ್ಪಾಯಿತು — ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    nlNote: "ನಾವು ನಿಮ್ಮ ಇಮೇಲ್ ಅನ್ನು ಎಂದೂ ಮಾರುವುದಿಲ್ಲ. ಡಬಲ್ ಆಪ್ಟ್-ಇನ್.",
    finalEyebrow: "ಇಂದೇ ಪ್ರಾರಂಭಿಸಿ",
    finalH2: "ನಿಮ್ಮ ಅಂಗಡಿಗೆ ಎಂದೂ ಮರೆಯದ ನೆನಪನ್ನು ಕೊಡಿ.",
    finalLede: "ಭಾರತದಾದ್ಯಂತ ಸಾವಿರಾರು ಅಂಗಡಿಗಳು ಸಾಲದ ಮೇಲೆ ನಡೆಯುತ್ತವೆ. ನಿಮ್ಮದನ್ನು Smart Digital Khata‌ ಮೇಲೆ ನಡೆಸಿ — ಆರಂಭ ಉಚಿತ, ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ, ಇಂದೇ.",
    finalNote: "ಈಗಾಗಲೇ ನಡೆಯುತ್ತಿದೆ [link]khata.dadashaik.com[/link]‌ನಲ್ಲಿ · ಯಾವುದೇ Android ಫೋನ್‌ನಲ್ಲಿ ನಡೆಯುತ್ತದೆ",
    getEyebrow: "ಆ್ಯಪ್ ಪಡೆಯಿರಿ",
    getH2: "ಎರಡು ಆ್ಯಪ್‌ಗಳು — ಕೌಂಟರ್‌ನ ಎರಡೂ ಬದಿಗೆ ಒಂದೊಂದು.",
    getLede: "ಯಾವುದೇ Android ಫೋನ್‌ನಲ್ಲಿ ಉಚಿತವಾಗಿ ಇನ್‌ಸ್ಟಾಲ್ ಮಾಡಿ. ಕಂಪ್ಯೂಟರ್ ಬೇಡ, Play Store ಖಾತೆಯೂ ಬೇಡ.",
    getCustT: "ಗ್ರಾಹಕರಿಗಾಗಿ",
    getCustP: "ಪ್ರತಿ ಅಂಗಡಿಯಲ್ಲಿ ನಿಮ್ಮ ಸಾಲವನ್ನು ನೋಡಿ ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಪಾವತಿಸಿ.",
    getCustBtn: "ಗ್ರಾಹಕ ಆ್ಯಪ್ ಪಡೆಯಿರಿ",
    getShopT: "ಅಂಗಡಿಯವರಿಗಾಗಿ",
    getShopP: "ನಿಮ್ಮ ಖಾತೆ, ವಸೂಲಾತಿ ಮತ್ತು ಆನ್‌ಲೈನ್ ಅಂಗಡಿ — ನಿಮ್ಮ ಜೇಬಿನಲ್ಲಿ.",
    getShopBtn: "ಅಂಗಡಿ ಆ್ಯಪ್ ಪಡೆಯಿರಿ",
    getNote: "Android · ಉಚಿತ · ಲಿಂಕ್ ಅನ್ನು ನಿಮ್ಮ ಫೋನ್‌ನಲ್ಲಿ ತೆರೆದು Install ಒತ್ತಿ.",
    footTagline: "ಪ್ರತಿ ಅಂಗಡಿ, ಈಗ ಡಿಜಿಟಲ್ · Every shop, now digital",
    footBlog: "ಬ್ಲಾಗ್",
    footCopy: "© Smart Digital Khata",
  },
  ml: {
    navSignIn: "സൈൻ ഇൻ",
    navStartFree: "സൗജന്യമായി തുടങ്ങൂ",
    langMenuLabel: "ഭാഷ തിരഞ്ഞെടുക്കൂ",
    heroFlag: "ഭാരതത്തിനായി ഒരുക്കിയത് · പട്ടണങ്ങളും ഗ്രാമങ്ങളും",
    heroH1: "നിങ്ങളുടെ കടയുടെ കണക്ക് — ഇനി ഫോണിൽ. അതുതന്നെ നിങ്ങൾക്ക് പണം [em]പിരിച്ചുതരുന്നു[/em].",
    heroSub: "ഡിജിറ്റൽ [b]കടം[/b] കണക്ക്, വേഗം പിരിവ് നടത്തുന്ന WhatsApp ഓർമ്മപ്പെടുത്തലുകൾ, ഉപഭോക്താക്കൾക്ക് ഓർഡർ ചെയ്യാവുന്ന ഒരു ഓൺലൈൻ കട — നിങ്ങളുടെ ഭാഷയിൽ, ഏത് ഫോണിലും, തുടങ്ങാൻ സൗജന്യം.",
    ctaWa: "🟢 WhatsApp-ൽ തുടങ്ങൂ",
    ctaSignup: "സൗജന്യമായി സൈൻ അപ്പ് ചെയ്യൂ",
    trust2g: "[b]2G[/b]-യിലും പ്രവർത്തിക്കും",
    trustLangs: "[b]10[/b] ഭാഷകൾ",
    trustNoPc: "കമ്പ്യൂട്ടർ വേണ്ട",
    trustFree: "തുടങ്ങാൻ [b]സൗജന്യം[/b]",
    phTitle: "ഇന്നത്തെ കണക്ക്",
    phName1: "സീത ദേവി",
    phAmt1: "₹560 ബാക്കി",
    phName2: "രമേഷ് കുമാർ",
    phAmt2: "₹0 അടച്ചു",
    phBubble: "നമസ്കാരം സീതച്ചേച്ചി 🙏 നിങ്ങൾക്ക് ₹560 ബാക്കിയുണ്ട്. ഇവിടെ നിന്ന് അടയ്ക്കൂ 👉",
    phSent: "അയച്ചു ✓✓",
    probEyebrow: "എല്ലാ കടയുടമയ്ക്കും അറിയാവുന്ന പ്രശ്നം",
    probH2: "കടലാസ് കണക്ക് മറക്കുന്നു. ഉപഭോക്താക്കളും മറക്കുന്നു.[br]അത് [em]നിങ്ങളുടെ[/em] പണം, വാതിലിലൂടെ പുറത്തുപോകുന്നു.",
    probLede: "അയഞ്ഞ താളുകൾ, മങ്ങിയ പെൻസിൽ, “എത്ര ബാക്കിയുണ്ടെന്ന് ഓർമ്മയില്ല.” കടം ചോദിക്കുന്നത് ബുദ്ധിമുട്ടും പതുക്കെയുമാണ് — അതിനാൽ ഓരോ കൗണ്ടറിലും, ഓരോ മാസവും കുറേശ്ശെ നഷ്ടപ്പെടുന്നു. Smart Digital Khata ആ കണക്കിനെ ഒരിക്കലും മങ്ങാത്ത ഓർമ്മയാക്കുന്നു, നിങ്ങൾക്കുവേണ്ടി ചോദിക്കുന്ന ഓർമ്മപ്പെടുത്തലാക്കുന്നു.",
    costEyebrow: "കടലാസ് കണക്കിന്റെ വില",
    costH2: "ദിവസവുമുള്ള ചെറിയ ചെറിയ നഷ്ടങ്ങൾ[br]ചേർന്ന് യഥാർത്ഥ പണമാകുന്നു.",
    costLede: "ഒരു മങ്ങിയ താൾ. “മറന്നുപോയ” ഒരു ഉപഭോക്താവ്. ബുദ്ധിമുട്ട് തോന്നിയതിനാൽ ഒരിക്കലും അയക്കാത്ത ഒരു ഓർമ്മപ്പെടുത്തൽ. ഒരു ദിവസത്തിൽ വലുതായി തോന്നില്ല — പക്ഷേ വർഷം മുഴുവൻ കൗണ്ടറിൽ കൂട്ടിയാൽ കഷ്ടപ്പെട്ട വരുമാനത്തിൽ വലിയ ദ്വാരം.",
    cost1Big: "~₹14,600",
    cost1Cl: "വർഷത്തിൽ നഷ്ടപ്പെട്ടത്, ദിവസവും വെറും [b]₹40 കടം[/b] വഴുതിപ്പോയാൽ — മറന്ന്, വായിക്കാതെ, അല്ലെങ്കിൽ ഒരിക്കലും പിരിക്കാതെ.",
    cost2Big: "3–5 മണിക്കൂർ",
    cost2Cl: "ആഴ്ചയിൽ കൈകൊണ്ട് കണക്ക് കൂട്ടുന്നതിൽ — ഉപഭോക്തൃസേവനത്തിനോ വിശ്രമത്തിനോ ഉപയോഗിക്കാവുന്ന സമയം.",
    cost3Big: "ബുദ്ധിമുട്ട്",
    cost3Cl: "അയൽക്കാരനോട് നേരിട്ട് പണം ചോദിക്കൽ. അതുകൊണ്ടുതന്നെ എത്രയോ കടങ്ങൾ നിശ്ശബ്ദമായി ഉപേക്ഷിക്കപ്പെടുന്നു.",
    costIllus: "ഉദാഹരണം മാത്രം — ഓരോ കടയും വ്യത്യസ്തം. കാര്യം കൃത്യമായ സംഖ്യയല്ല; കൈകൊണ്ടുള്ള ജോലി ദിവസവും നിശ്ശബ്ദമായി പണവും സമയവും ചോർത്തുന്നു എന്നതാണ്. Smart Digital Khata ആ ചോർച്ച അടയ്ക്കുന്നു.",
    pillEyebrow: "നിങ്ങൾക്ക് ലഭിക്കുന്നത്",
    pillH2: "മൂന്ന് കാര്യങ്ങൾ, ഒരേ ലളിതമായ ആപ്പ്",
    pill1H3: "നിങ്ങൾക്ക് തിരികെ തരുന്ന ഡിജിറ്റൽ കണക്ക്",
    pill1P: "സെക്കൻഡുകൾക്കുള്ളിൽ കടം എഴുതൂ. സ്വയമേവയുള്ള WhatsApp & SMS ഓർമ്മപ്പെടുത്തലുകൾ — ഉപഭോക്താവിന്റെ സ്വന്തം ഭാഷയിൽ — വേഗം പണം എത്തിക്കുന്നു. പണം, UPI അല്ലെങ്കിൽ ഓൺലൈൻ, എല്ലാം ഒരിടത്ത്.",
    pill1K: "വെറും കണക്കല്ല, പണവും →",
    pill2H3: "നിങ്ങളുടെ കട, ഇനി എല്ലാവർക്കും കാണാം",
    pill2P: "ഉപഭോക്താക്കൾക്ക് കണ്ട് ഓർഡർ ചെയ്യാവുന്ന ഓൺലൈൻ കട — പിക്കപ്പ്, സൗജന്യ ഡെലിവറി അല്ലെങ്കിൽ ഡെലിവറി ചാർജ് നിങ്ങൾ തിരഞ്ഞെടുക്കൂ. നിങ്ങളുടെ തെരുവിലെ പ്രാദേശിക കച്ചവടം, ഒരു മെട്രോ ക്വിക്-കൊമേഴ്സ് ആപ്പല്ല.",
    pill2K: "പുതിയ ഉപഭോക്താക്കൾ, നിങ്ങളുടെ വ്യവസ്ഥയിൽ →",
    pill3H3: "ശരിക്കും ഭാരതത്തിനായി ഒരുക്കിയത്",
    pill3P: "പത്ത് ഭാഷകൾ ശബ്ദത്തിൽ വായിച്ചുകേൾപ്പിക്കുന്നതോടൊപ്പം, നിങ്ങളുടെ ഭാഷയിൽ 1,600 സാധനങ്ങളുടെ പട്ടിക, 2G-യിൽ ഓഫ്‌ലൈനിലും പ്രവർത്തിക്കും — നിങ്ങളുടെ പോക്കറ്റിലുള്ള ദൈനംദിന ഫോണിൽത്തന്നെ. തുടങ്ങാൻ KYC ഇല്ല.",
    pill3K: "നിങ്ങളുടെ ഭാഷ, നിങ്ങളുടെ ഫോൺ →",
    bandEyebrow: "നമ്മുടെ സ്ഥാനം എവിടെ",
    bandH2: "B & C പട്ടണങ്ങൾക്കും ഗ്രാമങ്ങൾക്കുമായി —[br]മെട്രോകൾക്കല്ല.",
    bandQ: "പ്രാദേശികം-ആദ്യം, ലളിതം, നിങ്ങളുടേത്. കടയുടമ തന്നെ ഉടമയായി തുടരുന്നു — ഇത് കിരാണ ഇപ്പോൾത്തന്നെ പ്രവർത്തിക്കുന്ന രീതിയെ ബഹുമാനിക്കുന്ന, നിശ്ശബ്ദമായി ശക്തിപ്പെടുത്തുന്ന ഒരു ഉപകരണം. തകർച്ചയല്ല. അന്തസ്സോടെ ഡിജിറ്റലാകൽ.",
    bandStat1B: "10",
    bandStat1S: "ഭാഷകൾ, അതിൽ ഹിന്ദി, ബംഗാളി, ഗുജറാത്തി, മറാഠി, തമിഴ്, തെലുങ്ക്, കന്നഡ, മലയാളം & ഉർദു",
    bandStat2B: "1,600+",
    bandStat2S: "നിങ്ങളുടെ ഭാഷയിൽ തയ്യാർ പലവ്യഞ്ജന സാധനങ്ങൾ",
    bandStat3B: "ഓഫ്‌ലൈൻ",
    bandStat3S: "ദുർബല 2G-യിലും പ്രവർത്തിച്ച് സിങ്ക് ചെയ്യും",
    bandStat4B: "₹0",
    bandStat4S: "തുടങ്ങാൻ — കാർഡ് വേണ്ട, കമ്പ്യൂട്ടർ വേണ്ട",
    econEyebrow: "വലിയ ചിത്രം",
    econH2: "ഒരു കട ഡിജിറ്റലാക്കൂ, അപ്പോൾ എന്തോ[br]വലുത് ഊരിന് മുഴുവൻ സംഭവിക്കുന്നു.",
    econLede: "കിരാണ കട വെറും കച്ചവടമല്ല — അത് നാട്ടിന്റെ വിശ്വാസം, കടം, ദൈനംദിന ജീവനാഡിയാണ്. അത് ശക്തിപ്പെടുമ്പോൾ, അയൽപക്കം മുഴുവൻ അതോടൊപ്പം വളരുന്നു.",
    ec1H3: "പണം ഗ്രാമത്തിൽത്തന്നെ നിൽക്കുന്നു",
    ec1P: "ഉപഭോക്താവ് തെരുവിന്റെ അറ്റത്തുള്ള കടയിൽ നിന്ന് വാങ്ങുന്നു, രണ്ട് പട്ടണം അകലെയുള്ള ഗോഡൗണിൽ നിന്നല്ല. ലാഭവും — ഉപജീവനവും — ഊര് വിട്ട് പോകാതെ ഇവിടെത്തന്നെ നിൽക്കുന്നു.",
    ec2H3: "പണമൊഴുക്ക് വീണ്ടും ജീവൻ വയ്ക്കുന്നു",
    ec2P: "വേഗം പിരിച്ച കടം കുടുങ്ങിക്കിടന്ന മൂലധനത്തെ അഴിക്കുന്നു. കടയുടമയ്ക്ക് വേഗം സാധനം നിറയ്ക്കാം, ന്യായമായ കടം കൊടുക്കാം, കുറഞ്ഞ വരുമാനത്തിന്റെ മാസങ്ങളിലും അയൽക്കാരെ സേവിക്കാം.",
    ec3H3: "സ്വന്തം ഭാഷയിൽ അന്തസ്സ്",
    ec3P: "ഒരിക്കലും ഇംഗ്ലീഷ് സോഫ്റ്റ്‌വെയർ തൊടാത്ത കടയുടമ ഇപ്പോൾ തമിഴ്, തെലുങ്ക്, ഹിന്ദി അല്ലെങ്കിൽ ഉർദുവിൽ ആധുനിക കച്ചവടം നടത്തുന്നു — വായിച്ച്, കേട്ട്, മനസ്സിലാക്കപ്പെട്ട്. ശരിക്കും എല്ലാവരെയും ഉൾക്കൊള്ളുന്ന ഡിജിറ്റൽ ഉൾപ്പെടുത്തൽ.",
    ec4H3: "മൂലയിലെ കട നിലനിൽക്കുന്നു",
    ec4P: "വലിയ ചെയിനുകൾക്കും മെട്രോ ആപ്പുകൾക്കും എതിരെ, വിശ്വസ്ത പ്രാദേശിക കിരാണയ്ക്ക് അതേ ആധുനിക ഉപകരണങ്ങൾ കിട്ടുന്നു — സ്വന്തം ഫോണിൽത്തന്നെ. നിങ്ങളുടെ കുടുംബത്തിന് അറിയാവുന്ന കട, നാളേക്ക് തയ്യാർ.",
    econLine: "പിരിഞ്ഞ ഓരോ ഓർമ്മപ്പെടുത്തലും, പൂർത്തിയായ ഓരോ ഓർഡറും, ഊരിൽ നിൽക്കുന്ന ഓരോ രൂപയും — അതുതന്നെ ഗ്രാമ സമ്പദ്‌വ്യവസ്ഥയെ അൽപ്പം ശക്തിപ്പെടുത്തുന്നു, ഒരു കണക്ക് ഒരു തവണ.",
    stepsEyebrow: "ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു",
    stepsH2: "അഞ്ച് മിനിറ്റിൽ തയ്യാർ",
    step1H3: "നിങ്ങളുടെ മൊബൈലിൽ സൈൻ അപ്പ് ചെയ്യൂ",
    step1P: "നിങ്ങളുടെ ഫോൺ നമ്പറും ഒരു പാസ്‌വേഡോ PIN-ഓ മാത്രം. പിന്നീട് നമ്പർ മാറ്റൂ, കണക്ക് നഷ്ടപ്പെടാതെ.",
    step2H3: "ഉപഭോക്താക്കളും സാധനങ്ങളും ചേർക്കൂ",
    step2P: "ടൈപ്പ് ചെയ്യൂ, അല്ലെങ്കിൽ നിങ്ങളുടെ ഭാഷയിൽ കാണിക്കുന്ന 1,600 സാധനങ്ങളുടെ പട്ടികയിൽ നിന്ന് തിരഞ്ഞെടുക്കൂ. നിങ്ങളുടെ വില നിങ്ങൾ തന്നെ നിശ്ചയിക്കൂ.",
    step3H3: "എഴുതൂ, ഓർമ്മിപ്പിക്കൂ, വിൽക്കൂ",
    step3P: "കടം കുറിക്കൂ, WhatsApp-നെ പിരിവ് നടത്താൻ വിടൂ, നിങ്ങളുടെ കടയിൽ നിന്ന് ഓർഡർ എടുക്കൂ. എല്ലാം ഒരേ സ്ക്രീനിൽ കാണൂ.",
    langEyebrow: "നിങ്ങളുടെ ഭാഷയിൽ",
    langH2: "മുഴുവൻ ആപ്പും നിങ്ങളുടെ ഭാഷ സംസാരിക്കുന്നു",
    langLede: "നിങ്ങളുടെ സംസ്ഥാനത്തിന്റെ ഭാഷ തയ്യാറാകുമ്പോൾ, ഞങ്ങൾ അത് ഓണാക്കുന്നു — നിങ്ങളുടെ ഭാഷയിൽ ശ്രദ്ധയോടെ പരിശോധിച്ച്.",
    val1B: "നിങ്ങളുടെ ഡാറ്റ നിങ്ങളുടേത്.",
    val1S: "വിൽപ്പനയില്ല, സ്പാമില്ല. കണക്ക് എപ്പോൾ വേണമെങ്കിലും എക്സ്പോർട്ട് ചെയ്യൂ.",
    val2B: "കനത്ത ആപ്പല്ല.",
    val2S: "ചെറിയ ഡൗൺലോഡ്, വേഗം തുറക്കുന്നു, നിങ്ങളുടെ ഡാറ്റ പായ്ക്കിന് ലഘു.",
    val3B: "തുടങ്ങാൻ സൗജന്യം.",
    val3S: "ഇത് വ്യക്തമായി നിങ്ങൾക്ക് സമ്പാദിക്കുമ്പോൾ മാത്രം അപ്ഗ്രേഡ് ചെയ്യൂ.",
    val4B: "നിയന്ത്രണം നിങ്ങളുടെ കൈയിൽ.",
    val4S: "വില, ഡെലിവറി, ഓർമ്മപ്പെടുത്തലുകൾ — എപ്പോഴും നിങ്ങൾ തന്നെ തീരുമാനിക്കുന്നു.",
    nlEyebrow: "ന്യൂസ്‌ലെറ്റർ",
    nlH2: "കടയുടമകൾക്കുള്ള നുറുങ്ങുകൾ — നേരിട്ട് നിങ്ങളുടെ ഇൻബോക്സിലേക്ക്",
    nlLede: "കുറച്ച് ആഴ്ചകൾ കൂടുമ്പോൾ ഒരു ചെറിയ ഇമെയിൽ — കടം പിരിവ്, നിങ്ങളുടെ ഓൺലൈൻ കട, നിങ്ങളുടെ ഭാഷയിൽ പുതിയ ഫീച്ചറുകൾ. എപ്പോൾ വേണമെങ്കിലും അൺസബ്‌സ്ക്രൈബ് ചെയ്യൂ.",
    nlDoneT: "നിങ്ങളുടെ ഇൻബോക്സ് നോക്കൂ",
    nlDoneS: "സ്ഥിരീകരിക്കാൻ ഞങ്ങൾ നിങ്ങൾക്ക് ഒരു ലിങ്ക് അയച്ചിട്ടുണ്ട്.",
    nlPlaceholder: "നിങ്ങളുടെ ഇമെയിൽ",
    nlAriaEmail: "ഇമെയിൽ വിലാസം",
    nlAriaList: "പട്ടിക",
    nlOptCommunity: "കടയുടമകൾ",
    nlOptEcosystem: "പങ്കാളികൾ / വിതരണക്കാർ",
    nlSubmit: "സബ്‌സ്ക്രൈബ് ചെയ്യൂ",
    nlSending: "അയക്കുന്നു…",
    nlError: "എന്തോ പിഴച്ചു — ദയവായി വീണ്ടും ശ്രമിക്കൂ.",
    nlNote: "ഞങ്ങൾ നിങ്ങളുടെ ഇമെയിൽ ഒരിക്കലും വിൽക്കില്ല. ഡബിൾ ഓപ്റ്റ്-ഇൻ.",
    finalEyebrow: "ഇന്നുതന്നെ തുടങ്ങൂ",
    finalH2: "നിങ്ങളുടെ കടയ്ക്ക് ഒരിക്കലും മറക്കാത്ത ഓർമ്മ കൊടുക്കൂ.",
    finalLede: "ഭാരതത്തിലുടനീളം ആയിരക്കണക്കിന് കൗണ്ടറുകൾ കടത്തിൽ പ്രവർത്തിക്കുന്നു. നിങ്ങളുടേത് Smart Digital Khata-യിൽ പ്രവർത്തിപ്പിക്കൂ — തുടക്കം സൗജന്യം, നിങ്ങളുടെ ഭാഷയിൽ, ഇന്നുതന്നെ.",
    finalNote: "ഇപ്പോൾത്തന്നെ പ്രവർത്തിക്കുന്നു [link]khata.dadashaik.com[/link]-ൽ · ഏത് Android ഫോണിലും പ്രവർത്തിക്കും",
    getEyebrow: "ആപ്പ് നേടൂ",
    getH2: "രണ്ട് ആപ്പുകൾ — കൗണ്ടറിന്റെ ഇരു വശത്തിനും ഓരോന്ന്.",
    getLede: "ഏത് Android ഫോണിലും സൗജന്യമായി ഇൻസ്റ്റാൾ ചെയ്യൂ. കമ്പ്യൂട്ടർ വേണ്ട, Play Store അക്കൗണ്ടും വേണ്ട.",
    getCustT: "ഉപഭോക്താക്കൾക്ക്",
    getCustP: "ഓരോ കടയിലെയും നിങ്ങളുടെ കടം കണ്ട് ഒറ്റ ടാപ്പിൽ അടയ്ക്കൂ.",
    getCustBtn: "കസ്റ്റമർ ആപ്പ് നേടൂ",
    getShopT: "കടയുടമകൾക്ക്",
    getShopP: "നിങ്ങളുടെ കണക്ക്, പിരിവ്, ഓൺലൈൻ കട — നിങ്ങളുടെ പോക്കറ്റിൽ.",
    getShopBtn: "ഷോപ്പ് ആപ്പ് നേടൂ",
    getNote: "Android · സൗജന്യം · ലിങ്ക് നിങ്ങളുടെ ഫോണിൽ തുറന്ന് Install അമർത്തൂ.",
    footTagline: "ഓരോ കടയും, ഇനി ഡിജിറ്റൽ · Every shop, now digital",
    footBlog: "ബ്ലോഗ്",
    footCopy: "© Smart Digital Khata",
  },
  ur: {
    navSignIn: "سائن اِن",
    navStartFree: "مفت شروع کریں",
    langMenuLabel: "زبان منتخب کریں",
    heroFlag: "بھارت کے لیے بنایا گیا · قصبے اور گاؤں",
    heroH1: "آپ کی دکان کا کھاتہ — اب فون میں۔ اور یہی آپ کو پیسے [em]دِلواتا[/em] ہے۔",
    heroSub: "ڈیجیٹل [b]اُدھار[/b] کھاتہ، WhatsApp یاد دہانیاں جو جلد وصولی کرائیں، اور ایک آن لائن دکان جہاں سے گاہک آرڈر کریں — آپ کی زبان میں، کسی بھی فون پر، شروع کرنا مفت۔",
    ctaWa: "🟢 WhatsApp پر شروع کریں",
    ctaSignup: "مفت سائن اپ کریں",
    trust2g: "[b]2G[/b] پر چلے",
    trustLangs: "[b]10[/b] زبانیں",
    trustNoPc: "کمپیوٹر نہیں چاہیے",
    trustFree: "شروع کرنا [b]مفت[/b]",
    phTitle: "آج کا حساب",
    phName1: "سیتا دیوی",
    phAmt1: "₹560 باقی",
    phName2: "رمیش کمار",
    phAmt2: "₹0 جمع",
    phBubble: "السلام علیکم سیتا جی 🙏 آپ کے ₹560 باقی ہیں۔ یہاں سے ادا کریں 👉",
    phSent: "بھیج دیا ✓✓",
    probEyebrow: "ہر دکاندار کی جانی پہچانی مشکل",
    probH2: "کاغذی بہی کھاتہ بھول جاتا ہے۔ گاہک بھی بھول جاتے ہیں۔[br]اور وہ [em]آپ کے[/em] پیسے ہیں جو دروازے سے باہر چلے جاتے ہیں۔",
    probLede: "ڈھیلے صفحے، پھیکی پنسل، ”یاد نہیں کتنا باقی تھا۔“ اُدھار مانگنا عجیب اور سست لگتا ہے — تو ہر کاؤنٹر پر، ہر مہینے تھوڑا تھوڑا کھو جاتا ہے۔ Smart Digital Khata اس رجسٹر کو ایسی یادداشت بنا دیتا ہے جو کبھی پھیکی نہیں پڑتی، اور ایک یاد دہانی جو آپ کی طرف سے مانگ لیتی ہے۔",
    costEyebrow: "کاغذی رجسٹر کی قیمت",
    costH2: "روز کا چھوٹا چھوٹا نقصان[br]مل کر اصلی پیسہ بن جاتا ہے۔",
    costLede: "ایک پھیکا صفحہ۔ ایک گاہک جو ”بھول گیا۔“ ایک یاد دہانی جو عجیب لگنے پر کبھی بھیجی ہی نہیں گئی۔ ایک دن میں بڑا نہیں لگتا — مگر سال بھر کے کاؤنٹروں میں جوڑیں تو محنت کی کمائی میں بڑا سوراخ۔",
    cost1Big: "~₹14,600",
    cost1Cl: "سال بھر میں گنوایا، اگر روز صرف [b]₹40 کا اُدھار[/b] نکل جائے — بھولا، بغیر پڑھا، یا کبھی وصول ہی نہیں کیا۔",
    cost2Big: "3–5 گھنٹے",
    cost2Cl: "ہفتے میں ہاتھ سے بہی کھاتہ جوڑنے میں — وہ وقت جو گاہک کی خدمت یا آرام میں لگ سکتا تھا۔",
    cost3Big: "عجیب",
    cost3Cl: "پڑوسی سے آمنے سامنے پیسے مانگنا۔ اسی وجہ سے کتنے اُدھار چپ چاپ چھوڑ دیے جاتے ہیں۔",
    costIllus: "صرف مثال — ہر دکان الگ ہے۔ بات صحیح عدد کی نہیں؛ بات یہ ہے کہ ہاتھ کا کام روز چپ چاپ پیسہ اور وقت بہا دیتا ہے۔ Smart Digital Khata اس رساؤ کو روکتا ہے۔",
    pillEyebrow: "آپ کو کیا ملتا ہے",
    pillH2: "تین چیزیں، ایک آسان ایپ",
    pill1H3: "ڈیجیٹل کھاتہ جو آپ کو واپس دلاتا ہے",
    pill1P: "سیکنڈوں میں اُدھار لکھیں۔ خودکار WhatsApp اور SMS یاد دہانیاں — گاہک کی اپنی زبان میں — جلد پیسے دلاتی ہیں۔ نقد، UPI یا آن لائن، سب ایک ہی جگہ۔",
    pill1K: "صرف حساب نہیں، پیسے بھی →",
    pill2H3: "آپ کی دکان، اب سب کو نظر آئے",
    pill2P: "ایک آن لائن دکان جہاں گاہک دیکھیں اور آرڈر کریں — پک اپ، مفت ڈیلیوری یا ڈیلیوری چارج آپ طے کریں۔ آپ کی گلی کا مقامی کاروبار، کوئی میٹرو کوئک کامرس ایپ نہیں۔",
    pill2K: "نئے گاہک، آپ کی شرائط پر →",
    pill3H3: "واقعی بھارت کے لیے بنایا گیا",
    pill3P: "دس زبانیں آواز میں پڑھ کر سنانے کے ساتھ، آپ کی زبان میں 1,600 اشیاء کی فہرست، اور 2G پر آف لائن بھی چلے — اسی روزمرہ کے فون پر جو آپ کی جیب میں ہے۔ شروع کرنے کے لیے کوئی KYC نہیں۔",
    pill3K: "آپ کی زبان، آپ کا فون →",
    bandEyebrow: "ہماری جگہ کہاں",
    bandH2: "B اور C قصبوں اور گاؤں کے لیے —[br]میٹرو کے لیے نہیں۔",
    bandQ: "علاقائی-پہلے، ہلکا، اور آپ کا اپنا۔ دکاندار ہی مالک رہتا ہے — یہ ایسا آلہ ہے جو کریانہ کے موجودہ طریقے کا احترام کرتا ہے اور چپ چاپ مضبوط بناتا ہے۔ توڑ پھوڑ نہیں۔ عزت کے ساتھ ڈیجیٹل ہونا۔",
    bandStat1B: "10",
    bandStat1S: "زبانیں، جن میں ہندی، بنگالی، گجراتی، مراٹھی، تمل، تیلگو، کنڑ، ملیالم اور اردو",
    bandStat2B: "1,600+",
    bandStat2S: "آپ کی زبان میں تیار کریانہ اشیاء",
    bandStat3B: "آف لائن",
    bandStat3S: "کمزور 2G پر بھی چلے اور سنک ہو",
    bandStat4B: "₹0",
    bandStat4S: "شروع کرنے کے لیے — نہ کارڈ، نہ کمپیوٹر",
    econEyebrow: "بڑی تصویر",
    econH2: "ایک دکان کو ڈیجیٹل کریں، اور کچھ[br]بڑا پورے قصبے کے ساتھ ہوتا ہے۔",
    econLede: "کریانہ دکان صرف کاروبار نہیں — وہ محلے کا بھروسہ، اُدھار اور روز کی زندگی کی لکیر ہے۔ جب وہ مضبوط ہوتی ہے، تو پورا محلہ اس کے ساتھ بڑھتا ہے۔",
    ec1H3: "پیسہ گاؤں میں ہی رہے",
    ec1P: "گاہک گلی کے آخر والی دکان سے خریدے، دو شہر دور کے گودام سے نہیں۔ منافع — اور روزی — قصبہ چھوڑ کر جانے کے بجائے یہیں رہے۔",
    ec2H3: "نقدی کا بہاؤ پھر زندہ ہو",
    ec2P: "جلد وصول کیا اُدھار پھنسی ہوئی پونجی کھول دیتا ہے۔ دکاندار جلد مال بھر سکے، مناسب اُدھار دے سکے، اور کم کمائی کے مہینوں میں بھی پڑوسیوں کی خدمت کرتا رہے۔",
    ec3H3: "اپنی زبان میں عزت",
    ec3P: "ایک دکاندار جس نے کبھی انگریزی سافٹ ویئر کو ہاتھ نہیں لگایا، اب تمل، تیلگو، ہندی یا اردو میں جدید کاروبار چلاتا ہے — پڑھتا ہے، سنتا ہے، سمجھا جاتا ہے۔ ایسی ڈیجیٹل شمولیت جو واقعی سب کو ساتھ لے۔",
    ec4H3: "کونے کی دکان قائم رہے",
    ec4P: "بڑی چینوں اور میٹرو ایپس کے سامنے، بھروسے مند مقامی کریانہ کو وہی جدید آلات ملیں — اسی فون پر جو پہلے سے اس کے پاس ہے۔ آپ کے خاندان کی جانی پہچانی دکان، آنے والے کل کے لیے تیار۔",
    econLine: "ہر وصول ہوئی یاد دہانی، ہر پوری ہوئی آرڈر، ہر روپیہ جو قصبے میں رہے — یہی گاؤں کی معیشت کو تھوڑا مضبوط کرتا ہے، ایک کھاتہ ایک بار میں۔",
    stepsEyebrow: "یہ کیسے کام کرتا ہے",
    stepsH2: "پانچ منٹ میں شروع",
    step1H3: "اپنے موبائل سے سائن اپ کریں",
    step1P: "بس آپ کا فون نمبر اور ایک پاس ورڈ یا PIN۔ بعد میں نمبر بدلیں، کھاتہ کھوئے بغیر۔",
    step2H3: "گاہک اور اشیاء شامل کریں",
    step2P: "ٹائپ کریں، یا آپ کی زبان میں دکھنے والی 1,600 اشیاء کی فہرست سے چنیں۔ اپنے دام خود طے کریں۔",
    step3H3: "لکھیں، یاد دلائیں، بیچیں",
    step3P: "اُدھار نوٹ کریں، WhatsApp کو وصولی کرنے دیں، اور اپنی دکان سے آرڈر لیں۔ سب ایک ہی اسکرین پر دیکھیں۔",
    langEyebrow: "آپ کی زبان میں",
    langH2: "پوری ایپ آپ کی زبان بولتی ہے",
    langLede: "اور جب آپ کے صوبے کی زبان تیار ہوتی ہے، ہم اسے چالو کر دیتے ہیں — آپ کی زبان میں غور سے جانچ کر۔",
    val1B: "آپ کا ڈیٹا آپ کا ہے۔",
    val1S: "نہ بیچنا، نہ اسپام۔ اپنا کھاتہ کبھی بھی ایکسپورٹ کریں۔",
    val2B: "کوئی بھاری ایپ نہیں۔",
    val2S: "چھوٹا ڈاؤن لوڈ، جلد کھلے، آپ کے ڈیٹا پیک پر ہلکا۔",
    val3B: "شروع کرنا مفت۔",
    val3S: "اپ گریڈ تبھی جب یہ صاف آپ کے لیے کمانے لگے۔",
    val4B: "قابو آپ کے ہاتھ۔",
    val4S: "دام، ڈیلیوری، یاد دہانیاں — ہمیشہ آپ طے کریں۔",
    nlEyebrow: "نیوز لیٹر",
    nlH2: "دکانداروں کے لیے تجاویز — سیدھے آپ کے اِن باکس میں",
    nlLede: "ہر کچھ ہفتوں میں ایک چھوٹا ای میل — اُدھار وصولی، آن لائن دکان اور آپ کی زبان میں نئے فیچر۔ کبھی بھی اَن سبسکرائب کریں۔",
    nlDoneT: "اپنا اِن باکس دیکھیں",
    nlDoneS: "تصدیق کے لیے ہم نے آپ کو ایک لنک بھیجا ہے۔",
    nlPlaceholder: "آپ کا ای میل",
    nlAriaEmail: "ای میل پتہ",
    nlAriaList: "فہرست",
    nlOptCommunity: "دکاندار",
    nlOptEcosystem: "پارٹنر / تقسیم کار",
    nlSubmit: "سبسکرائب کریں",
    nlSending: "بھیجا جا رہا…",
    nlError: "کچھ گڑبڑ ہوئی — براہ کرم دوبارہ کوشش کریں۔",
    nlNote: "ہم آپ کا ای میل کبھی نہیں بیچیں گے۔ ڈبل آپٹ اِن۔",
    finalEyebrow: "آج سے شروع کریں",
    finalH2: "اپنی دکان کو ایسی یادداشت دیں جو کبھی نہ بھولے۔",
    finalLede: "بھارت بھر کے ہزاروں کاؤنٹر اُدھار پر چلتے ہیں۔ اپنے کو Smart Digital Khata پر چلائیں — شروع مفت، آپ کی زبان میں، آج ہی۔",
    finalNote: "پہلے سے چالو [link]khata.dadashaik.com[/link] پر · کسی بھی Android فون پر چلے",
    getEyebrow: "ایپ حاصل کریں",
    getH2: "دو ایپ — کاؤنٹر کے ہر طرف کے لیے ایک۔",
    getLede: "کسی بھی Android فون پر مفت انسٹال کریں۔ نہ کمپیوٹر، نہ Play Store اکاؤنٹ کی ضرورت۔",
    getCustT: "گاہکوں کے لیے",
    getCustP: "ہر دکان پر اپنا ادھار دیکھیں اور ایک ٹیپ میں ادا کریں۔",
    getCustBtn: "گاہک ایپ حاصل کریں",
    getShopT: "دکانداروں کے لیے",
    getShopP: "آپ کا کھاتہ، وصولی اور آن لائن دکان — آپ کی جیب میں۔",
    getShopBtn: "دکان ایپ حاصل کریں",
    getNote: "Android · مفت · لنک اپنے فون پر کھولیں اور Install دبائیں۔",
    footTagline: "ہر دکان، اب ڈیجیٹل · Every shop, now digital",
    footBlog: "بلاگ",
    footCopy: "© Smart Digital Khata",
  },
};
