const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const customerRoutes = require('./customer.routes');
const ledgerRoutes = require('./ledger.routes');
const shopRoutes = require('./shop.routes');
const dashboardRoutes = require('./dashboard.routes');
const notificationRoutes = require('./notification.routes');
const reportRoutes = require('./report.routes');
const dueAgingRoutes = require('./due-aging.routes');
const subscriptionRoutes = require('./subscription.routes');
const paymentRoutes = require('./payment.routes');
const aiInsightsRoutes = require('./ai-insights.routes');
const auditLogRoutes = require('./audit-log.routes');
const riskEngineRoutes = require('./risk-engine.routes');
const whatsappRoutes = require('./whatsapp.routes');
const recoveryPredictionRoutes = require('./recovery-prediction.routes');
const customerSegmentationRoutes = require('./customer-segmentation.routes');
const smartNudgeRoutes = require('./smart-nudge.routes');

router.use('/auth', authRoutes);
router.use('/customers', customerRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/shops', shopRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
router.use('/due-aging', dueAgingRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/payments', paymentRoutes);
router.use('/ai-insights', aiInsightsRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/risk-engine', riskEngineRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/recovery-prediction', recoveryPredictionRoutes);
router.use('/customer-segmentation', customerSegmentationRoutes);
router.use('/smart-nudges', smartNudgeRoutes);

module.exports = router;
