const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const customerRoutes = require('./customer.routes');
const ledgerRoutes = require('./ledger.routes');
const shopRoutes = require('./shop.routes');
const dashboardRoutes = require('./dashboard.routes');
const notificationRoutes = require('./notification.routes');
const reportRoutes = require('./report.routes');
const dueAgingRoutes = require('./due-aging.routes');
const subscriptionRoutes = require('./subscription.routes');
const paymentRoutes = require('./payment.routes');
const aiInsightsRoutes = require('./ai-insights.routes');
const auditLogRoutes = require('./audit-log.routes');
const riskEngineRoutes = require('./risk-engine.routes');
const whatsappRoutes = require('./whatsapp.routes');
const recoveryPredictionRoutes = require('./recovery-prediction.routes');
const customerSegmentationRoutes = require('./customer-segmentation.routes');
const smartNudgeRoutes = require('./smart-nudge.routes');
const collectionTimingRoutes = require('./collection-timing.routes');
const escalationEngineRoutes = require('./escalation-engine.routes');
const merchantHealthRoutes = require('./merchant-health.routes');
const defaulterForecastRoutes = require('./defaulter-forecast.routes');
const portfolioRiskRoutes = require('./portfolio-risk.routes');
const creditLimitRoutes = require('./credit-limit.routes');
const merchantLendingRoutes = require('./merchant-lending.routes');
const revenueForecastRoutes = require('./revenue-forecast.routes');
const fraudDetectionRoutes = require('./fraud-detection.routes');
const cashflowIntelligenceRoutes = require('./cashflow-intelligence.routes');
const complianceMonitorRoutes = require('./compliance-monitor.routes');
const merchantBenchmarkRoutes = require('./merchant-benchmark.routes');
const merchantAiCopilotRoutes = require('./merchant-ai-copilot.routes');
const smartAutomationRoutes = require('./smart-automation.routes');

router.use('/auth', authRoutes);
router.use('/customers', customerRoutes);
router.use('/ledger', ledgerRoutes);
router.use('/shops', shopRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/notifications', notificationRoutes);
router.use('/reports', reportRoutes);
router.use('/due-aging', dueAgingRoutes);
router.use('/subscriptions', subscriptionRoutes);
router.use('/payments', paymentRoutes);
router.use('/ai-insights', aiInsightsRoutes);
router.use('/audit-logs', auditLogRoutes);
router.use('/risk-engine', riskEngineRoutes);
router.use('/whatsapp', whatsappRoutes);
router.use('/recovery-prediction', recoveryPredictionRoutes);
router.use('/customer-segmentation', customerSegmentationRoutes);
router.use('/smart-nudges', smartNudgeRoutes);
router.use('/collection-timing', collectionTimingRoutes);
router.use('/escalation-engine', escalationEngineRoutes);
router.use('/merchant-health', merchantHealthRoutes);
router.use('/defaulter-forecast', defaulterForecastRoutes);
router.use('/portfolio-risk', portfolioRiskRoutes);
router.use('/credit-limit', creditLimitRoutes);
router.use('/merchant-lending', merchantLendingRoutes);
router.use('/revenue-forecast', revenueForecastRoutes);
router.use('/fraud-detection', fraudDetectionRoutes);
router.use('/cashflow-intelligence', cashflowIntelligenceRoutes);
router.use('/compliance-monitor', complianceMonitorRoutes);
router.use('/merchant-benchmark', merchantBenchmarkRoutes);
router.use('/merchant-ai-copilot', merchantAiCopilotRoutes);
router.use('/smart-automation', smartAutomationRoutes);

module.exports = router;
